/* ============================================================
   英语单词联想网络  —  你只需要编辑这个文件就能加词！
   ------------------------------------------------------------
   思路：按「意思」联想，而不是按词性。每个概念是一个中心，
        相关的词挂在周围。同一个词出现在多个概念里时，
        它会自动变成连接两团的「桥」（比如 gulp 连「吃」和「喝」）。

   结构：
     "概念名（中文 英文）": {
       related: ["可关联到的其它概念名", ...],   // 可留空 []
       words: [
         ["word", "中文释义；和近义词的区别", "例句（可留空 '')"],
         ...
       ]
     },

   想加新词？复制一段改成你的内容即可。注意：
   - 所有引号用英文 ""，逗号用英文 ,
   - 想让两个词产生联系，只要把它们放进同一个概念，或在 related 里互相写上对方
   - 同名词写在不同概念里 = 自动桥接，不会重复
   ============================================================ */

const DATA = {

  /* ---------- 动作：吃喝 ---------- */
  "吃 eat": { related:["喝 drink","嘴 mouth","食物 food","做饭 cook"], words:[
    ["eat", "吃（通用）", "eat lunch"],
    ["swallow", "吞咽：不嚼直接咽下去", "swallow a pill"],
    ["chew", "咀嚼：用牙磨碎", "chew gum"],
    ["bite", "咬：用牙咬住或咬下一口", "bite an apple"],
    ["gnaw", "啃：持续地咬硬物", "a dog gnawing a bone"],
    ["nibble", "小口啃、一点点咬", "nibble on a biscuit"],
    ["munch", "大声咀嚼、嚼得有声", "munch crisps"],
    ["devour", "狼吞虎咽、吃光", "devour a whole pizza"],
    ["lick", "舔", "lick an ice cream"],
    ["taste", "品尝、尝味道", "taste the soup"],
    ["gulp", "大口吞食", "gulp down food"],
  ]},
  "喝 drink": { related:["吃 eat","容器 cup"], words:[
    ["drink", "喝（通用）", "drink water"],
    ["sip", "小口抿、慢慢喝", "sip hot tea"],
    ["gulp", "大口吞咽（咕咚一下）", "gulp down a glass of water"],
    ["swallow", "咽下去", "hard to swallow"],
    ["slurp", "出声地吸食、唏哩呼噜喝", "slurp noodles"],
    ["taste", "品尝（饮品也用）", "taste the wine"],
  ]},

  /* ---------- 动作：移动 / 感官 ---------- */
  "移动 / 走 move": { related:["路 road","快 fast"], words:[
    ["walk", "走、步行", "walk to school"],
    ["run", "跑", "run fast"],
    ["jog", "慢跑（健身）", "jog in the park"],
    ["sprint", "短距离冲刺、全力跑", "sprint to the finish"],
    ["stroll", "悠闲地散步", "stroll along the beach"],
    ["wander", "漫步、闲逛（无目的）", "wander around town"],
    ["march", "齐步走、行军", "soldiers marching"],
    ["hike", "徒步、远足", "hike up a mountain"],
    ["crawl", "爬行", "a baby crawling"],
    ["limp", "一瘸一拐地走", "limp after the injury"],
    ["stride", "大步走", "stride confidently"],
    ["climb", "攀爬", "climb a ladder"],
  ]},
  "看 look": { related:["眼睛 eye"], words:[
    ["look", "（主动）看，强调动作", "look at the board"],
    ["see", "看见，强调结果", "I can see the sea."],
    ["watch", "观看会动的东西", "watch a film"],
    ["stare", "盯着看（久、专注）", "stare at the screen"],
    ["glare", "怒视、瞪", "glare angrily"],
    ["glance", "瞥一眼（快、短）", "glance at the clock"],
    ["gaze", "凝视（出神、欣赏）", "gaze at the stars"],
    ["peep", "偷看、窥视", "peep through the keyhole"],
    ["glimpse", "瞥见、一瞥（名/动）", "catch a glimpse of"],
    ["observe", "观察（仔细研究）", "observe behaviour"],
  ]},
  "说 speak": { related:["嘴 mouth"], words:[
    ["say", "说（后接内容）", "say sorry"],
    ["tell", "告诉（后接人）", "tell me a story"],
    ["speak", "讲（语言/正式发言）", "speak French"],
    ["talk", "交谈、聊（双向）", "talk to a friend"],
    ["whisper", "低语、耳语", "whisper a secret"],
    ["shout", "喊、大声叫", "shout for help"],
    ["yell", "吼叫（更激动）", "yell in anger"],
    ["scream", "尖叫", "scream in fear"],
    ["mutter", "嘀咕、小声抱怨", "mutter under one's breath"],
    ["mumble", "含糊不清地说", "mumble an answer"],
    ["argue", "争论、争辩", "argue about money"],
  ]},

  /* ---------- 动作：表情 / 情绪反应 ---------- */
  "笑 laugh": { related:[], words:[
    ["laugh", "（出声）笑", "laugh out loud"],
    ["smile", "微笑（不出声）", "smile at someone"],
    ["giggle", "咯咯地笑、傻笑", "giggle nervously"],
    ["grin", "咧嘴大笑", "grin with joy"],
    ["chuckle", "轻声笑、暗笑", "chuckle quietly"],
    ["smirk", "得意/嘲讽地笑", "smirk smugly"],
    ["beam", "笑容满面", "beam with pride"],
  ]},
  "哭 cry": { related:[], words:[
    ["cry", "哭（通用）", "cry loudly"],
    ["weep", "（默默）流泪、哭泣", "weep for joy"],
    ["sob", "抽泣、啜泣", "sob uncontrollably"],
    ["whimper", "呜咽、低声哭", "whimper in pain"],
    ["wail", "嚎啕大哭、哀号", "wail in grief"],
  ]},

  /* ---------- 动作：手部 ---------- */
  "拿 / 握 hold": { related:["扔 throw","推拉 push / pull","给 give"], words:[
    ["hold", "拿着、握住、抱", "hold a cup"],
    ["grab", "抓住（突然、快）", "grab my hand"],
    ["grasp", "紧紧抓住、握牢", "grasp the rope"],
    ["grip", "（用力）握紧", "grip the wheel"],
    ["clutch", "（紧张地）抱紧、攥住", "clutch a bag"],
    ["seize", "夺取、抓住（机会/物）", "seize the chance"],
    ["snatch", "一把夺过、抢", "snatch the phone"],
    ["hug", "拥抱", "hug a friend"],
    ["carry", "搬运、携带（拿着移动）", "carry a bag"],
    ["lift", "举起、抬", "lift a box"],
  ]},
  "扔 throw": { related:["拿 / 握 hold"], words:[
    ["throw", "扔、投（通用）", "throw a ball"],
    ["toss", "轻轻抛、随手扔", "toss a coin"],
    ["hurl", "猛力投掷", "hurl a rock"],
    ["fling", "（用力、随意）甩出", "fling the door open"],
    ["cast", "投、撒（网/钓线，正式）", "cast a net"],
  ]},
  "打 hit": { related:["破坏 break"], words:[
    ["hit", "打、击中（通用）", "hit the target"],
    ["strike", "击打（正式/突然）", "strike a match"],
    ["slap", "扇、掌掴", "slap his face"],
    ["punch", "（用拳）猛击", "punch the bag"],
    ["beat", "（反复）打、揍", "beat a drum"],
    ["knock", "敲（门）", "knock on the door"],
    ["tap", "轻拍、轻敲", "tap on the shoulder"],
    ["smash", "猛砸、砸碎", "smash a window"],
  ]},
  "推拉 push / pull": { related:["拿 / 握 hold"], words:[
    ["push", "推", "push the door"],
    ["pull", "拉", "pull the rope"],
    ["drag", "拖、拽（费力地）", "drag a heavy box"],
    ["shove", "猛推、粗暴地推", "shove someone aside"],
    ["tug", "用力拉一下、拽", "tug at her sleeve"],
    ["lift", "举起、抬", "lift weights"],
    ["carry", "搬运、携带", "carry a bag"],
  ]},
  "切 cut": { related:["做饭 cook"], words:[
    ["cut", "切、割（通用）", "cut the cake"],
    ["slice", "切片", "slice bread"],
    ["chop", "剁、砍（用力、成块）", "chop vegetables"],
    ["carve", "雕刻、切（肉）", "carve a turkey"],
    ["trim", "修剪", "trim the hedge"],
    ["peel", "削皮", "peel an apple"],
    ["mince", "切碎、绞碎", "minced meat"],
  ]},

  /* ---------- 动作：头脑 / 休息 ---------- */
  "想 think": { related:[], words:[
    ["think", "想、认为（通用）", "think hard"],
    ["consider", "考虑（经思量）", "consider the options"],
    ["ponder", "沉思、深思", "ponder a question"],
    ["reflect", "反思、回想", "reflect on the past"],
    ["wonder", "想知道、纳闷", "wonder what happened"],
    ["imagine", "想象", "imagine a perfect day"],
    ["guess", "猜测", "guess the answer"],
    ["doubt", "怀疑", "doubt the news"],
  ]},
  "睡 sleep": { related:["累 tired"], words:[
    ["sleep", "睡觉（通用）", "sleep eight hours"],
    ["nap", "小睡、打盹", "take a nap"],
    ["doze", "打瞌睡（不知不觉）", "doze off"],
    ["slumber", "酣睡（文学）", "deep slumber"],
    ["rest", "休息", "rest for a while"],
    ["yawn", "打哈欠", "yawn sleepily"],
  ]},

  /* ---------- 动作：更多 ---------- */
  "给 give": { related:["拿 / 握 hold"], words:[
    ["give", "给（通用）", "give a gift"],
    ["offer", "（主动）提供、提议", "offer help"],
    ["provide", "提供（正式），provide sb with", "provide food"],
    ["hand", "递给（手递手）", "hand me the salt"],
    ["present", "赠予、颁发（正式）", "present an award"],
    ["donate", "捐赠", "donate money to charity"],
    ["deliver", "递送、配送", "deliver a parcel"],
    ["supply", "供应（持续、批量）", "supply electricity"],
  ]},
  "做 / 造 make": { related:[], words:[
    ["make", "做、制作（通用）", "make a cake"],
    ["do", "做、从事（动作/事务）", "do homework"],
    ["create", "创造、创作", "create art"],
    ["build", "建造、搭建", "build a house"],
    ["produce", "生产、制造", "produce cars"],
    ["construct", "建造（正式、大型）", "construct a bridge"],
    ["manufacture", "（工厂）批量制造", "manufacture goods"],
  ]},
  "帮助 help": { related:[], words:[
    ["help", "帮助（通用）", "help a friend"],
    ["assist", "协助（正式）", "assist the manager"],
    ["aid", "援助（多指物资/正式）", "aid the victims"],
    ["support", "支持、扶持", "support a cause"],
    ["back", "支持、力挺", "back the plan"],
  ]},
  "开始 start": { related:["结束 finish"], words:[
    ["start", "开始（通用）", "start work"],
    ["begin", "开始（稍正式）", "begin a journey"],
    ["commence", "开始（很正式、书面）", "commence proceedings"],
    ["launch", "发起、推出、发射", "launch a product"],
    ["initiate", "发起、启动（正式）", "initiate a project"],
  ]},
  "结束 finish": { related:["开始 start"], words:[
    ["finish", "完成、结束（通用）", "finish dinner"],
    ["end", "结束、终结", "end a war"],
    ["complete", "完成（达到完整）", "complete the form"],
    ["stop", "停止", "stop talking"],
    ["cease", "停止（正式）", "cease fire"],
    ["conclude", "结束、总结（正式）", "conclude the speech"],
  ]},
  "增加 increase": { related:["减少 reduce"], words:[
    ["increase", "增加（通用）", "increase production"],
    ["rise", "上升（不及物，不接宾语）", "Prices rise."],
    ["raise", "提高（及物，接宾语）", "raise prices"],
    ["grow", "增长（自然、逐渐）", "The economy grows."],
    ["expand", "扩张、扩大", "expand the business"],
    ["boost", "促进、提升", "boost sales"],
    ["soar", "猛涨、剧增", "Prices soared."],
  ]},
  "减少 reduce": { related:["增加 increase"], words:[
    ["reduce", "减少（主动降低）", "reduce costs"],
    ["decrease", "减少（数量下降，正式）", "Sales decreased."],
    ["decline", "下降、衰退（渐、常负面）", "Population declines."],
    ["drop", "（突然）下降、下跌", "Temperatures dropped."],
    ["diminish", "削弱、减小（重要性）", "diminish its value"],
    ["shrink", "缩小、收缩", "The market shrank."],
  ]},
  "改变 change": { related:[], words:[
    ["change", "改变（通用）", "change your mind"],
    ["alter", "（部分、细节）更改", "alter a dress"],
    ["modify", "（小幅）修改、调整", "modify the design"],
    ["transform", "（彻底）改变、变形", "transform the city"],
    ["adjust", "调整、调节", "adjust the volume"],
    ["convert", "转换、改装", "convert dollars to euros"],
  ]},
  "学习 learn": { related:["教 teach"], words:[
    ["learn", "学会、掌握（结果）", "learn English"],
    ["study", "学习、钻研（过程）", "study hard"],
    ["master", "精通", "master a skill"],
    ["revise", "复习（英式）", "revise for exams"],
    ["memorize", "背诵、记住", "memorize a poem"],
    ["practise", "练习（英式拼写）", "practise the piano"],
  ]},
  "教 teach": { related:["学习 learn"], words:[
    ["teach", "教（通用）", "teach maths"],
    ["instruct", "指导、传授（正式）", "instruct students"],
    ["train", "培训、训练", "train new staff"],
    ["educate", "教育", "educate children"],
    ["coach", "辅导、教练", "coach a team"],
    ["tutor", "（一对一）辅导", "tutor a student"],
  ]},
  "找 find": { related:[], words:[
    ["find", "找到（通用）", "find the keys"],
    ["discover", "发现（已存在的）", "discover a cave"],
    ["locate", "定位、找到（确切位置）", "locate the fault"],
    ["detect", "察觉、探测", "detect a leak"],
    ["search", "搜寻（动作，search for）", "search for clues"],
    ["seek", "寻求（正式）", "seek advice"],
  ]},
  "买卖 buy / sell": { related:["钱 money"], words:[
    ["buy", "买（通用）", "buy a ticket"],
    ["purchase", "购买（正式）", "purchase goods"],
    ["sell", "卖", "sell a car"],
    ["trade", "交易、买卖", "trade stocks"],
    ["bargain", "讨价还价", "bargain over the price"],
    ["afford", "买得起、负担得起", "can't afford it"],
  ]},
  "做饭 cook": { related:["吃 eat","食物 food","切 cut"], words:[
    ["cook", "做饭、烹饪（通用）", "cook dinner"],
    ["boil", "煮、煮沸", "boil an egg"],
    ["fry", "煎、炒、炸", "fry an egg"],
    ["bake", "烘焙（烤箱、面点）", "bake bread"],
    ["roast", "烤（肉、整块）", "roast a chicken"],
    ["grill", "炙烤、烧烤", "grill steak"],
    ["steam", "蒸", "steam vegetables"],
  ]},
  "清洁 clean": { related:[], words:[
    ["clean", "打扫、弄干净（通用）", "clean the room"],
    ["wash", "洗", "wash your hands"],
    ["wipe", "擦（用布/纸）", "wipe the table"],
    ["scrub", "用力擦洗、刷", "scrub the floor"],
    ["rinse", "冲洗、漂洗", "rinse the cup"],
    ["sweep", "扫", "sweep the floor"],
    ["mop", "拖（地）", "mop the kitchen"],
  ]},
  "破坏 break": { related:["修 fix","打 hit"], words:[
    ["break", "弄坏、打破（通用）", "break a glass"],
    ["smash", "猛砸、砸碎", "smash a window"],
    ["crack", "（出现裂纹）裂开", "The cup cracked."],
    ["shatter", "（碎成片）粉碎", "The mirror shattered."],
    ["destroy", "彻底摧毁", "destroy the building"],
    ["ruin", "毁掉、糟蹋", "ruin the party"],
  ]},
  "修 fix": { related:["破坏 break"], words:[
    ["fix", "修理（通用、口语）", "fix the car"],
    ["repair", "修理（较正式）", "repair the roof"],
    ["mend", "修补（衣物、小物）", "mend a sock"],
    ["restore", "修复、还原（旧物）", "restore a painting"],
  ]},
  "触摸 touch": { related:[], words:[
    ["touch", "触摸、碰（通用）", "touch the screen"],
    ["feel", "（用手）感觉、摸", "feel the fabric"],
    ["stroke", "抚摸（轻、来回）", "stroke a cat"],
    ["pat", "轻拍", "pat the dog"],
    ["rub", "揉、摩擦", "rub your eyes"],
    ["scratch", "挠、抓", "scratch an itch"],
  ]},
  "掉落 fall": { related:[], words:[
    ["fall", "落下、跌倒（通用）", "fall down"],
    ["drop", "掉落（物从手中）", "drop a plate"],
    ["collapse", "倒塌、坍塌", "The roof collapsed."],
    ["tumble", "滚落、摔倒", "tumble down the stairs"],
    ["slip", "滑倒、打滑", "slip on the ice"],
    ["trip", "绊倒、绊一下", "trip over a wire"],
  ]},

  /* ---------- 情绪（形容词）---------- */
  "高兴 happy": { related:["难过 sad","兴奋 excited"], words:[
    ["happy", "高兴、幸福（通用）", "a happy child"],
    ["glad", "（一时）高兴的", "glad to see you"],
    ["pleased", "满意、欣慰", "pleased with the result"],
    ["delighted", "非常高兴（语气强）", "delighted to help"],
    ["cheerful", "开朗、兴高采烈", "a cheerful mood"],
    ["joyful", "充满喜悦", "a joyful celebration"],
    ["thrilled", "激动、兴奋极了", "thrilled about the trip"],
    ["content", "知足、满足", "content with life"],
  ]},
  "难过 sad": { related:["高兴 happy"], words:[
    ["sad", "难过、伤心（通用）", "feel sad"],
    ["unhappy", "不开心的", "an unhappy marriage"],
    ["upset", "心烦、难受", "upset about the news"],
    ["gloomy", "忧郁、阴沉", "a gloomy mood"],
    ["miserable", "痛苦、悲惨", "feel miserable"],
    ["depressed", "沮丧、抑郁", "deeply depressed"],
    ["sorrowful", "悲伤的（文学）", "a sorrowful song"],
  ]},
  "生气 angry": { related:[], words:[
    ["angry", "生气（通用）", "angry with me"],
    ["annoyed", "恼火、烦", "annoyed by the noise"],
    ["irritated", "被惹恼、不耐烦", "irritated by delays"],
    ["cross", "（口语）生气的", "She's cross with you."],
    ["mad", "（口语）气疯了", "mad at him"],
    ["furious", "暴怒、狂怒", "furious about the lie"],
    ["outraged", "义愤填膺", "outraged by injustice"],
  ]},
  "害怕 afraid": { related:[], words:[
    ["afraid", "害怕（通用，作表语）", "afraid of dogs"],
    ["scared", "（受惊）害怕（口语）", "scared of the dark"],
    ["frightened", "受惊吓的", "frightened by the storm"],
    ["terrified", "极度恐惧（语气强）", "terrified of flying"],
    ["nervous", "紧张、不安", "nervous before the exam"],
    ["anxious", "焦虑、担忧", "anxious about the future"],
    ["panic", "惊慌（名/动）", "panic in the crowd"],
  ]},
  "累 tired": { related:["睡 sleep"], words:[
    ["tired", "累（通用）", "feel tired"],
    ["exhausted", "精疲力竭（语气强）", "completely exhausted"],
    ["weary", "疲惫、厌倦", "weary after work"],
    ["sleepy", "困、想睡", "sleepy in class"],
    ["fatigued", "疲劳的（正式/医学）", "physically fatigued"],
  ]},
  "喜欢 like": { related:["讨厌 hate"], words:[
    ["like", "喜欢（通用）", "like music"],
    ["love", "热爱、爱", "love painting"],
    ["enjoy", "享受、喜爱（+doing）", "enjoy reading"],
    ["adore", "极喜爱、崇拜", "adore her"],
    ["fancy", "喜欢、想要（英式口语）", "fancy a coffee"],
    ["prefer", "更喜欢", "prefer tea to coffee"],
  ]},
  "讨厌 hate": { related:["喜欢 like"], words:[
    ["hate", "讨厌、恨（通用）", "hate Mondays"],
    ["dislike", "不喜欢（较温和、正式）", "dislike the noise"],
    ["loathe", "厌恶（强烈）", "loathe violence"],
    ["detest", "憎恶（正式）", "detest lying"],
    ["despise", "鄙视、看不起", "despise cowards"],
  ]},
  "惊讶 surprised": { related:[], words:[
    ["surprised", "惊讶的（通用）", "surprised by the news"],
    ["amazed", "惊叹、惊奇（多褒）", "amazed at the view"],
    ["astonished", "震惊、大为吃惊", "astonished by the result"],
    ["shocked", "震惊（多负面）", "shocked by the accident"],
    ["stunned", "惊呆、目瞪口呆", "stunned into silence"],
    ["startled", "（突然）吓一跳", "startled by a noise"],
  ]},
  "兴奋 excited": { related:["高兴 happy"], words:[
    ["excited", "兴奋、激动", "excited about the trip"],
    ["thrilled", "激动极了", "thrilled with the gift"],
    ["eager", "渴望的、急切的", "eager to learn"],
    ["enthusiastic", "热情的、热心的", "enthusiastic about sport"],
    ["keen", "热衷的（英式）", "keen on football"],
  ]},

  /* ---------- 描述（形容词）---------- */
  "大 big": { related:["小 small"], words:[
    ["big", "大（口语、通用）", "a big house"],
    ["large", "大（尺寸/数量，正式）", "a large population"],
    ["huge", "巨大的", "a huge success"],
    ["enormous", "庞大的", "an enormous building"],
    ["giant", "巨型的", "a giant wave"],
    ["massive", "（块头）巨大、沉重", "a massive rock"],
    ["vast", "广阔的（面积）", "a vast desert"],
  ]},
  "小 small": { related:["大 big"], words:[
    ["small", "小（尺寸，通用）", "a small room"],
    ["little", "小、少（带感情）", "a cute little dog"],
    ["tiny", "微小的", "a tiny insect"],
    ["miniature", "微型的", "a miniature model"],
    ["minor", "次要的、轻微的", "a minor problem"],
    ["slight", "细微的、轻微的", "a slight change"],
  ]},
  "漂亮 beautiful": { related:[], words:[
    ["beautiful", "美丽的（通用）", "a beautiful view"],
    ["pretty", "漂亮的（多指女性/小巧）", "a pretty girl"],
    ["handsome", "英俊的（多指男性）", "a handsome man"],
    ["gorgeous", "极美的、惊艳", "you look gorgeous"],
    ["attractive", "有吸引力的", "an attractive design"],
    ["lovely", "可爱、宜人的", "a lovely day"],
    ["stunning", "令人惊叹的美", "a stunning sunset"],
    ["cute", "可爱的", "a cute baby"],
  ]},
  "聪明 clever": { related:[], words:[
    ["clever", "聪明、机灵（反应快）", "a clever idea"],
    ["smart", "聪明的（口语，美式）", "a smart kid"],
    ["intelligent", "有智慧的（正式）", "an intelligent answer"],
    ["bright", "（尤指年轻人）聪明", "a bright student"],
    ["wise", "明智、有阅历的", "a wise decision"],
    ["brilliant", "才华横溢、绝妙", "a brilliant scientist"],
  ]},
  "快 fast": { related:["移动 / 走 move"], words:[
    ["fast", "快（速度，形/副）", "a fast car"],
    ["quick", "快速的（短暂、迅速）", "a quick look"],
    ["rapid", "迅速的（变化/增长）", "rapid growth"],
    ["swift", "敏捷的（书面）", "a swift response"],
    ["speedy", "快速的、迅速的", "a speedy recovery"],
  ]},
  "好 good": { related:["坏 bad"], words:[
    ["good", "好（通用）", "a good idea"],
    ["great", "很棒的", "a great movie"],
    ["excellent", "优秀的、极好的", "excellent work"],
    ["wonderful", "精彩、美好的", "a wonderful time"],
    ["fantastic", "了不起的（口语）", "a fantastic result"],
    ["superb", "一流的、卓越的", "superb quality"],
    ["fine", "不错的、挺好的", "a fine performance"],
  ]},
  "坏 bad": { related:["好 good"], words:[
    ["bad", "坏（通用）", "a bad habit"],
    ["awful", "糟糕的、可怕的", "an awful smell"],
    ["terrible", "很糟、骇人的", "a terrible mistake"],
    ["horrible", "可怕、令人不快的", "horrible weather"],
    ["poor", "差的、质量低的", "poor quality"],
    ["nasty", "讨厌的、恶劣的", "a nasty surprise"],
  ]},
  "重要 important": { related:[], words:[
    ["important", "重要的（通用）", "an important decision"],
    ["significant", "显著、有重大意义的", "a significant change"],
    ["crucial", "至关重要、决定性的", "a crucial role"],
    ["vital", "至关重要的（语气强）", "vital information"],
    ["essential", "必不可少的", "essential for life"],
    ["key", "关键的", "a key factor"],
    ["major", "主要的、重大的", "a major issue"],
  ]},
  "安静 quiet": { related:[], words:[
    ["quiet", "安静的（通用）", "a quiet room"],
    ["silent", "寂静、无声的", "fall silent"],
    ["calm", "平静的、镇定的", "stay calm"],
    ["peaceful", "宁静、和平的", "a peaceful village"],
    ["still", "静止的、不动的", "sit still"],
  ]},
  "冷 cold": { related:["热 hot"], words:[
    ["cold", "冷的（通用）", "a cold day"],
    ["cool", "凉爽的（偏舒适）", "a cool breeze"],
    ["chilly", "微冷、有点凉", "a chilly morning"],
    ["freezing", "极冷、冰冻的", "freezing weather"],
    ["icy", "冰冷的、结冰的", "an icy road"],
  ]},
  "热 hot": { related:["冷 cold"], words:[
    ["hot", "热的（通用）", "hot water"],
    ["warm", "温暖的（舒适）", "a warm room"],
    ["boiling", "滚烫的、沸腾的", "boiling hot"],
    ["scorching", "灼热、酷热", "a scorching day"],
    ["mild", "温和的（天气）", "a mild winter"],
  ]},
  "强 strong": { related:["弱 weak"], words:[
    ["strong", "强壮、强大的（通用）", "a strong man"],
    ["powerful", "强有力的、有权势的", "a powerful engine"],
    ["mighty", "强大的（文学/夸张）", "a mighty army"],
    ["tough", "坚韧的、强硬的", "a tough material"],
    ["sturdy", "结实的、坚固的", "a sturdy table"],
  ]},
  "弱 weak": { related:["强 strong"], words:[
    ["weak", "虚弱、弱的（通用）", "feel weak"],
    ["feeble", "（身体）虚弱无力的", "a feeble voice"],
    ["fragile", "易碎的、脆弱的", "fragile glass"],
    ["frail", "（老弱）孱弱的", "a frail old man"],
    ["delicate", "娇弱、精细的", "delicate skin"],
  ]},

  /* ---------- 物品：穿戴 ---------- */
  "鞋 shoes": { related:["衣服 clothes"], words:[
    ["shoe", "鞋（统称）", "a pair of shoes"],
    ["slipper", "拖鞋、便鞋", "wear slippers at home"],
    ["boot", "靴子", "rain boots"],
    ["sandal", "凉鞋", "summer sandals"],
    ["sneaker", "运动鞋（美式）", "white sneakers"],
    ["trainer", "运动鞋（英式）", "a pair of trainers"],
    ["heel", "高跟鞋", "high heels"],
    ["loafer", "乐福鞋、平底便鞋", "leather loafers"],
  ]},
  "衣服 clothes": { related:["鞋 shoes"], words:[
    ["shirt", "衬衫", "a white shirt"],
    ["coat", "外套、大衣", "a winter coat"],
    ["jacket", "夹克", "a leather jacket"],
    ["sweater", "毛衣", "a wool sweater"],
    ["hoodie", "连帽衫", "a grey hoodie"],
    ["dress", "连衣裙", "a summer dress"],
    ["skirt", "半身裙", "a short skirt"],
    ["trousers", "裤子（英式）", "smart trousers"],
    ["suit", "西装、套装", "a business suit"],
  ]},

  /* ---------- 物品：住与家具 ---------- */
  "房子 house": { related:["家具 furniture","房间 room"], words:[
    ["house", "房子（独栋）", "a big house"],
    ["home", "家（含归属感）", "go home"],
    ["flat", "公寓（英式）", "rent a flat"],
    ["apartment", "公寓（美式）", "a city apartment"],
    ["cottage", "小屋、村舍", "a country cottage"],
    ["villa", "别墅", "a seaside villa"],
    ["mansion", "豪宅", "a grand mansion"],
    ["cabin", "小木屋", "a log cabin"],
  ]},
  "家具 furniture": { related:["房子 house"], words:[
    ["chair", "椅子", "sit on a chair"],
    ["sofa", "沙发", "a leather sofa"],
    ["stool", "凳子（无靠背）", "a bar stool"],
    ["bench", "长椅", "a park bench"],
    ["table", "桌子", "a dining table"],
    ["desk", "书桌、办公桌", "a writing desk"],
    ["shelf", "架子", "a book shelf"],
  ]},
  "房间 room": { related:["房子 house"], words:[
    ["bedroom", "卧室", "a cosy bedroom"],
    ["kitchen", "厨房", "cook in the kitchen"],
    ["bathroom", "浴室、卫生间", "use the bathroom"],
    ["living room", "客厅", "relax in the living room"],
    ["hallway", "走廊、门厅", "a narrow hallway"],
    ["attic", "阁楼", "store boxes in the attic"],
    ["basement", "地下室", "a damp basement"],
  ]},

  /* ---------- 物品：出行 ---------- */
  "路 road": { related:["移动 / 走 move","车 vehicle"], words:[
    ["road", "道路（通用、车行）", "a busy road"],
    ["street", "街道（城市、两旁有房）", "a quiet street"],
    ["path", "小路、小径", "a garden path"],
    ["lane", "小巷、车道", "a country lane"],
    ["avenue", "大街、林荫道", "a tree-lined avenue"],
    ["highway", "公路、干道", "a busy highway"],
    ["trail", "（山野）小道", "a hiking trail"],
    ["alley", "胡同、后巷", "a dark alley"],
  ]},
  "车 vehicle": { related:["路 road"], words:[
    ["car", "小汽车", "drive a car"],
    ["bus", "公交车", "take the bus"],
    ["truck", "卡车（美式）", "a delivery truck"],
    ["lorry", "卡车（英式）", "a heavy lorry"],
    ["van", "厢式货车、面包车", "a delivery van"],
    ["taxi", "出租车", "call a taxi"],
    ["motorcycle", "摩托车", "ride a motorcycle"],
  ]},

  /* ---------- 物品：容器与随身 ---------- */
  "容器 cup": { related:["喝 drink","餐具 cutlery"], words:[
    ["cup", "杯子（带把、喝热饮）", "a cup of tea"],
    ["mug", "马克杯（大、厚）", "a coffee mug"],
    ["glass", "玻璃杯", "a glass of water"],
    ["bottle", "瓶子", "a water bottle"],
    ["jar", "罐子（广口、带盖）", "a jam jar"],
    ["bowl", "碗", "a bowl of soup"],
    ["jug", "水壶、有嘴的罐", "a milk jug"],
    ["kettle", "烧水壶", "boil the kettle"],
  ]},
  "包 bag": { related:[], words:[
    ["bag", "包、袋（通用）", "a shopping bag"],
    ["backpack", "双肩背包", "a school backpack"],
    ["handbag", "手提包（女士）", "a leather handbag"],
    ["suitcase", "行李箱", "pack a suitcase"],
    ["purse", "钱包（美式）/小手袋", "a small purse"],
    ["wallet", "钱夹（男士）", "a leather wallet"],
    ["sack", "麻袋、大袋", "a sack of potatoes"],
  ]},

  /* ---------- 身体部位 ---------- */
  "嘴 mouth": { related:["吃 eat","说 speak","脸 face"], words:[
    ["mouth", "嘴", "open your mouth"],
    ["lip", "嘴唇", "red lips"],
    ["tongue", "舌头", "stick out your tongue"],
    ["teeth", "牙齿（复数；单数 tooth）", "brush your teeth"],
    ["jaw", "下巴、颌", "a strong jaw"],
    ["throat", "喉咙", "a sore throat"],
    ["gum", "牙龈", "healthy gums"],
  ]},
  "眼睛 eye": { related:["看 look","脸 face"], words:[
    ["eye", "眼睛", "blue eyes"],
    ["eyebrow", "眉毛", "raise an eyebrow"],
    ["eyelash", "睫毛", "long eyelashes"],
    ["eyelid", "眼皮", "heavy eyelids"],
    ["pupil", "瞳孔（也指学生）", "dilated pupils"],
  ]},
  "脸 face": { related:["嘴 mouth","眼睛 eye","身体 body"], words:[
    ["face", "脸", "wash your face"],
    ["nose", "鼻子", "a runny nose"],
    ["ear", "耳朵", "cover your ears"],
    ["cheek", "脸颊", "rosy cheeks"],
    ["chin", "下巴", "a pointed chin"],
    ["forehead", "额头", "wrinkle your forehead"],
    ["eyebrow", "眉毛", "raise an eyebrow"],
  ]},
  "身体 body": { related:["脸 face"], words:[
    ["head", "头", "nod your head"],
    ["arm", "手臂", "raise your arm"],
    ["leg", "腿", "stretch your legs"],
    ["hand", "手", "wave your hand"],
    ["foot", "脚（复数 feet）", "on foot"],
    ["shoulder", "肩膀", "a sore shoulder"],
    ["knee", "膝盖", "bend your knees"],
    ["chest", "胸部", "chest pain"],
  ]},

  /* ---------- 物品：餐厨 / 学习 / 设备 ---------- */
  "餐具 cutlery": { related:["吃 eat","容器 cup"], words:[
    ["knife", "刀", "a sharp knife"],
    ["fork", "叉子", "use a fork"],
    ["spoon", "勺子", "a soup spoon"],
    ["plate", "盘子", "a dinner plate"],
    ["chopsticks", "筷子", "eat with chopsticks"],
    ["napkin", "餐巾", "a paper napkin"],
  ]},
  "文具 stationery": { related:[], words:[
    ["pen", "钢笔、笔", "write with a pen"],
    ["pencil", "铅笔", "a sharp pencil"],
    ["notebook", "笔记本", "a thick notebook"],
    ["eraser", "橡皮", "use an eraser"],
    ["ruler", "尺子", "a plastic ruler"],
    ["marker", "记号笔", "a black marker"],
  ]},
  "电子设备 device": { related:[], words:[
    ["phone", "手机、电话", "answer the phone"],
    ["computer", "电脑", "use a computer"],
    ["laptop", "笔记本电脑", "a thin laptop"],
    ["tablet", "平板电脑", "read on a tablet"],
    ["screen", "屏幕", "a touch screen"],
    ["keyboard", "键盘", "type on a keyboard"],
  ]},

  /* ---------- 自然 / 类别族 ---------- */
  "天气 weather": { related:[], words:[
    ["rain", "雨", "heavy rain"],
    ["drizzle", "毛毛雨", "a light drizzle"],
    ["shower", "阵雨", "a sudden shower"],
    ["snow", "雪", "fresh snow"],
    ["storm", "暴风雨", "a thunderstorm"],
    ["fog", "雾", "thick fog"],
    ["breeze", "微风", "a gentle breeze"],
    ["thunder", "雷", "thunder and lightning"],
  ]},
  "食物 food": { related:["吃 eat","做饭 cook"], words:[
    ["meal", "一餐、餐食", "a healthy meal"],
    ["snack", "零食、点心", "a quick snack"],
    ["dish", "一道菜", "a tasty dish"],
    ["feast", "盛宴、大餐", "a wedding feast"],
    ["cuisine", "菜系、烹饪风格", "Italian cuisine"],
    ["recipe", "食谱", "follow a recipe"],
  ]},
  "水果 fruit": { related:[], words:[
    ["apple", "苹果", "a red apple"],
    ["banana", "香蕉", "a ripe banana"],
    ["orange", "橙子", "a juicy orange"],
    ["grape", "葡萄", "a bunch of grapes"],
    ["pear", "梨", "a sweet pear"],
    ["peach", "桃子", "a soft peach"],
    ["strawberry", "草莓", "fresh strawberries"],
    ["mango", "芒果", "a ripe mango"],
  ]},
  "动物 animal": { related:[], words:[
    ["dog", "狗", "a pet dog"],
    ["cat", "猫", "a black cat"],
    ["horse", "马", "ride a horse"],
    ["cow", "牛", "a dairy cow"],
    ["sheep", "羊", "a flock of sheep"],
    ["pig", "猪", "a fat pig"],
    ["rabbit", "兔子", "a white rabbit"],
    ["chicken", "鸡", "feed the chickens"],
  ]},
  "植物 plant": { related:[], words:[
    ["tree", "树", "an old tree"],
    ["flower", "花", "pick flowers"],
    ["grass", "草", "green grass"],
    ["bush", "灌木", "a rose bush"],
    ["leaf", "叶子", "fallen leaves"],
    ["root", "根", "deep roots"],
    ["branch", "树枝", "a broken branch"],
    ["seed", "种子", "plant seeds"],
  ]},
  "时间 time": { related:[], words:[
    ["second", "秒", "wait a second"],
    ["minute", "分钟", "five minutes"],
    ["hour", "小时", "an hour later"],
    ["day", "天", "a sunny day"],
    ["week", "周", "next week"],
    ["month", "月", "last month"],
    ["year", "年", "this year"],
    ["decade", "十年", "the past decade"],
  ]},
  "钱 money": { related:["买卖 buy / sell"], words:[
    ["money", "钱（统称、不可数）", "earn money"],
    ["cash", "现金", "pay in cash"],
    ["coin", "硬币", "a gold coin"],
    ["note", "纸币（英式；美式 bill）", "a ten-pound note"],
    ["currency", "货币（某国的）", "foreign currency"],
    ["fund", "资金、基金", "raise funds"],
    ["salary", "薪水", "a monthly salary"],
  ]},

  /* ---------- 动作：更多（第二批）---------- */
  "离开 leave": { related:["到达 arrive"], words:[
    ["leave", "离开（通用）", "leave home"],
    ["depart", "出发、启程（正式）", "The train departs at 9."],
    ["exit", "退出、离场", "exit the building"],
    ["quit", "退出、辞职", "quit the job"],
    ["withdraw", "撤退、退出（正式）", "withdraw from the race"],
    ["flee", "逃离、逃走", "flee the country"],
  ]},
  "到达 arrive": { related:["离开 leave","移动 / 走 move"], words:[
    ["arrive", "到达（通用，arrive at/in）", "arrive at the station"],
    ["reach", "抵达（及物，直接接地点）", "reach the top"],
    ["approach", "接近、靠近", "approach the gate"],
    ["land", "降落、着陆", "The plane landed."],
    ["enter", "进入", "enter the room"],
  ]},
  "跳 jump": { related:["移动 / 走 move"], words:[
    ["jump", "跳（通用）", "jump over the fence"],
    ["leap", "跃、纵身一跳", "leap into the air"],
    ["hop", "单脚跳、蹦", "hop on one foot"],
    ["bounce", "弹跳、反弹", "The ball bounces."],
    ["skip", "蹦跳；跳过", "skip down the street"],
    ["spring", "猛地跳起", "spring to your feet"],
  ]},
  "飞 fly": { related:[], words:[
    ["fly", "飞（通用）", "Birds fly."],
    ["soar", "高飞、翱翔", "eagles soaring"],
    ["glide", "滑翔（平稳）", "glide through the air"],
    ["hover", "（在空中）盘旋、悬停", "a hovering helicopter"],
    ["flutter", "振翅、飘动", "butterflies fluttering"],
    ["dive", "俯冲、潜入", "dive into the water"],
  ]},
  "开关 open / close": { related:[], words:[
    ["open", "打开", "open the door"],
    ["close", "关闭（通用）", "close the window"],
    ["shut", "关上（语气更重/口语）", "shut the gate"],
    ["lock", "锁上", "lock the door"],
    ["seal", "密封、封住", "seal the envelope"],
    ["unlock", "解锁、打开", "unlock the phone"],
  ]},
  "藏 hide": { related:["展示 show"], words:[
    ["hide", "躲藏、隐藏（通用）", "hide behind a tree"],
    ["conceal", "隐藏、掩盖（正式）", "conceal the truth"],
    ["cover", "遮盖、盖住", "cover your face"],
    ["bury", "埋、掩埋", "bury treasure"],
    ["mask", "掩饰、遮掩", "mask the smell"],
  ]},
  "展示 show": { related:["藏 hide"], words:[
    ["show", "展示、给…看（通用）", "show your ticket"],
    ["display", "陈列、展示", "display goods"],
    ["reveal", "揭示、透露", "reveal a secret"],
    ["exhibit", "展览、展出（正式）", "exhibit paintings"],
    ["demonstrate", "演示、证明", "demonstrate how it works"],
    ["present", "呈现、展示", "present the findings"],
  ]},
  "问 ask": { related:["回答 answer"], words:[
    ["ask", "问、要求（通用）", "ask a question"],
    ["inquire", "询问、打听（正式）", "inquire about prices"],
    ["question", "质问、盘问", "question a suspect"],
    ["request", "请求（正式、礼貌）", "request help"],
    ["beg", "乞求、恳求", "beg for mercy"],
    ["demand", "强烈要求", "demand an answer"],
  ]},
  "回答 answer": { related:["问 ask"], words:[
    ["answer", "回答（通用）", "answer the question"],
    ["reply", "回复、答复", "reply to an email"],
    ["respond", "回应、作出反应（正式）", "respond quickly"],
    ["react", "反应、回应", "react to the news"],
  ]},
  "选择 choose": { related:["决定 decide"], words:[
    ["choose", "选择（通用）", "choose a colour"],
    ["select", "挑选（较正式、慎重）", "select the best one"],
    ["pick", "挑、捡（口语）", "pick a card"],
    ["opt", "选择（opt for / to）", "opt for tea"],
    ["elect", "选举、推选", "elect a leader"],
  ]},
  "决定 decide": { related:["选择 choose"], words:[
    ["decide", "决定（通用）", "decide to go"],
    ["determine", "确定、决定（正式）", "determine the cause"],
    ["resolve", "下决心、决意", "resolve to quit"],
    ["settle", "定下来、解决", "settle the matter"],
  ]},
  "检查 check": { related:[], words:[
    ["check", "检查、核对（通用）", "check your work"],
    ["examine", "检查、审查（仔细）", "examine the evidence"],
    ["inspect", "视察、检验（正式）", "inspect the factory"],
    ["test", "测试", "test the machine"],
    ["review", "审阅、回顾", "review the report"],
    ["verify", "核实、证实", "verify the facts"],
  ]},
  "赢 / 输 win / lose": { related:["打 hit"], words:[
    ["win", "赢、获胜", "win a match"],
    ["lose", "输、失去", "lose the game"],
    ["beat", "打败、击败（及物）", "beat the rival"],
    ["defeat", "击败、战胜（正式）", "defeat the enemy"],
    ["conquer", "征服、攻克", "conquer a country"],
    ["triumph", "获胜、成功", "triumph over difficulties"],
  ]},
  "救 save": { related:[], words:[
    ["save", "拯救、挽救（通用）", "save a life"],
    ["rescue", "营救、解救", "rescue the climbers"],
    ["protect", "保护、防护", "protect the children"],
    ["guard", "看守、守卫", "guard the gate"],
    ["shield", "遮护、保护", "shield from the sun"],
    ["defend", "防御、保卫", "defend the city"],
  ]},
  "跟随 follow": { related:["路 road"], words:[
    ["follow", "跟随、跟着（通用）", "follow me"],
    ["chase", "追逐、追赶", "chase a thief"],
    ["pursue", "追求、追捕（正式）", "pursue a dream"],
    ["trail", "尾随、跟踪", "trail a suspect"],
    ["track", "追踪、跟踪", "track an animal"],
  ]},
  "读 read": { related:["看 look","写 write"], words:[
    ["read", "读、阅读（通用）", "read a book"],
    ["scan", "扫读、快速查看", "scan the headlines"],
    ["skim", "略读、浏览大意", "skim the article"],
    ["browse", "随便翻阅、浏览", "browse a magazine"],
    ["proofread", "校对", "proofread an essay"],
  ]},
  "写 write": { related:["读 read","文具 stationery"], words:[
    ["write", "写（通用）", "write a letter"],
    ["scribble", "乱写、潦草地写", "scribble a note"],
    ["jot", "匆匆记下（jot down）", "jot down a number"],
    ["compose", "创作、撰写", "compose a song"],
    ["draft", "起草、草拟", "draft a plan"],
    ["sign", "签名", "sign your name"],
  ]},
  "画 draw": { related:[], words:[
    ["draw", "画（线条、素描）", "draw a picture"],
    ["sketch", "素描、速写", "sketch a face"],
    ["paint", "绘画、上色", "paint a landscape"],
    ["doodle", "（随手）涂鸦", "doodle in a margin"],
    ["trace", "描摹、临摹", "trace the outline"],
  ]},
  "呼吸 breathe": { related:[], words:[
    ["breathe", "呼吸（通用）", "breathe deeply"],
    ["inhale", "吸气", "inhale the fresh air"],
    ["exhale", "呼气", "exhale slowly"],
    ["gasp", "喘气、倒吸气", "gasp for air"],
    ["pant", "气喘吁吁", "pant after running"],
    ["sigh", "叹气", "sigh with relief"],
  ]},

  /* ---------- 描述：更多反义组 ---------- */
  "脏 dirty": { related:["清洁 clean"], words:[
    ["dirty", "脏的（通用）", "dirty hands"],
    ["filthy", "肮脏的（语气强）", "a filthy room"],
    ["messy", "凌乱的、邋遢的", "a messy desk"],
    ["grubby", "（不洗）邋遢的", "grubby clothes"],
    ["muddy", "泥泞的、沾泥的", "muddy boots"],
    ["dusty", "布满灰尘的", "a dusty shelf"],
  ]},
  "湿 wet": { related:["干 dry"], words:[
    ["wet", "湿的（通用）", "wet hair"],
    ["damp", "潮湿的（微湿、发霉感）", "a damp cellar"],
    ["moist", "湿润的（适度，偏褒）", "moist cake"],
    ["soaked", "湿透的", "soaked to the skin"],
    ["humid", "（空气）闷热潮湿的", "humid weather"],
  ]},
  "干 dry": { related:["湿 wet"], words:[
    ["dry", "干的（通用）", "dry clothes"],
    ["arid", "干旱的（气候）", "an arid desert"],
    ["parched", "干涸的、焦渴的", "parched land"],
    ["dehydrated", "脱水的", "feel dehydrated"],
  ]},
  "安全 safe": { related:["危险 dangerous"], words:[
    ["safe", "安全的（通用）", "a safe place"],
    ["secure", "牢靠的、安全的", "a secure password"],
    ["protected", "受保护的", "a protected area"],
    ["harmless", "无害的", "a harmless insect"],
  ]},
  "危险 dangerous": { related:["安全 safe"], words:[
    ["dangerous", "危险的（通用）", "a dangerous road"],
    ["risky", "冒险的、有风险的", "a risky decision"],
    ["hazardous", "有危害的（正式）", "hazardous chemicals"],
    ["perilous", "凶险的（文学）", "a perilous journey"],
  ]},
  "富 rich": { related:["穷 poor","钱 money"], words:[
    ["rich", "富有的（通用）", "a rich family"],
    ["wealthy", "富裕的（较正式）", "a wealthy businessman"],
    ["affluent", "富足的（社会、地区）", "an affluent neighbourhood"],
    ["well-off", "宽裕的、小康的", "a well-off family"],
  ]},
  "穷 poor": { related:["富 rich"], words:[
    ["poor", "贫穷的（通用）", "a poor village"],
    ["broke", "身无分文的（口语）", "I'm broke."],
    ["needy", "贫困的、需救济的", "needy families"],
    ["impoverished", "赤贫的（正式）", "an impoverished region"],
  ]},
  "勇敢 brave": { related:[], words:[
    ["brave", "勇敢的（通用）", "a brave soldier"],
    ["courageous", "有勇气的（正式）", "a courageous act"],
    ["bold", "大胆的、无畏的", "a bold move"],
    ["fearless", "无所畏惧的", "a fearless leader"],
    ["daring", "敢于冒险的", "a daring escape"],
  ]},
  "诚实 honest": { related:[], words:[
    ["honest", "诚实的（通用）", "an honest answer"],
    ["truthful", "讲真话的", "a truthful account"],
    ["sincere", "真诚的", "sincere thanks"],
    ["frank", "坦率的、直言的", "to be frank"],
    ["genuine", "真挚的、真心的", "a genuine smile"],
  ]},
  "困惑 confused": { related:[], words:[
    ["confused", "困惑的（通用）", "confused by the map"],
    ["puzzled", "迷惑不解的", "a puzzled look"],
    ["baffled", "（彻底）难住的", "baffled by the question"],
    ["bewildered", "不知所措的", "bewildered tourists"],
    ["perplexed", "困惑费解的（正式）", "a perplexed expression"],
  ]},
  "担心 worried": { related:["害怕 afraid"], words:[
    ["worried", "担心的（通用）", "worried about exams"],
    ["concerned", "关切的、担忧的", "concerned for safety"],
    ["anxious", "焦虑不安的", "anxious about the future"],
    ["uneasy", "不安的、忐忑的", "feel uneasy"],
    ["troubled", "烦恼的、忧心的", "a troubled mind"],
  ]},
  "老 / 旧 old": { related:["新 new"], words:[
    ["old", "老的、旧的（通用）", "an old book"],
    ["ancient", "古代的、远古的", "ancient ruins"],
    ["antique", "古董的（有年代价值）", "an antique clock"],
    ["aged", "年老的（人）", "an aged man"],
    ["elderly", "上了年纪的（礼貌）", "elderly people"],
    ["worn", "磨损的、用旧的", "worn shoes"],
  ]},
  "新 new": { related:["老 / 旧 old"], words:[
    ["new", "新的（通用）", "a new phone"],
    ["modern", "现代的、新式的", "modern art"],
    ["recent", "近期的、最近的", "recent news"],
    ["fresh", "新鲜的、崭新的", "fresh bread"],
    ["novel", "新颖的、新奇的", "a novel idea"],
    ["brand-new", "全新的", "a brand-new car"],
  ]},

  /* ---------- 词族：出行 / 人 / 类别 ---------- */
  "旅行 trip": { related:["移动 / 走 move","车 vehicle"], words:[
    ["trip", "短途（往返）旅行", "a business trip"],
    ["journey", "（单程、较长）旅程", "a long journey"],
    ["travel", "旅行（泛指、不可数）", "foreign travel"],
    ["voyage", "海上/太空航行", "an ocean voyage"],
    ["tour", "观光、巡回（多地点）", "a city tour"],
    ["expedition", "（科考/探险）远征", "a polar expedition"],
  ]},
  "职业 job-titles": { related:["工资 / 收入 salary"], words:[
    ["teacher", "教师", "a maths teacher"],
    ["doctor", "医生", "see a doctor"],
    ["nurse", "护士", "a kind nurse"],
    ["engineer", "工程师", "a software engineer"],
    ["lawyer", "律师", "hire a lawyer"],
    ["chef", "厨师", "a famous chef"],
    ["pilot", "飞行员", "an airline pilot"],
    ["farmer", "农民", "a hardworking farmer"],
  ]},
  "工资 / 收入 salary": { related:["职业 job-titles","钱 money"], words:[
    ["salary", "（按月/年的）薪水", "a high salary"],
    ["wage", "（按时/周的）工资", "an hourly wage"],
    ["income", "收入（各来源总和）", "household income"],
    ["earnings", "（劳动）所得", "annual earnings"],
    ["bonus", "奖金", "a year-end bonus"],
  ]},
  "运动 sport": { related:[], words:[
    ["football", "足球", "play football"],
    ["basketball", "篮球", "a basketball game"],
    ["tennis", "网球", "a tennis court"],
    ["swimming", "游泳", "go swimming"],
    ["running", "跑步", "go running"],
    ["cycling", "骑行", "cycling in the park"],
    ["boxing", "拳击", "a boxing match"],
  ]},
  "乐器 instrument": { related:[], words:[
    ["piano", "钢琴", "play the piano"],
    ["guitar", "吉他", "an acoustic guitar"],
    ["violin", "小提琴", "play the violin"],
    ["drum", "鼓", "beat a drum"],
    ["flute", "长笛", "play the flute"],
    ["trumpet", "小号", "blow a trumpet"],
  ]},
  "颜色 colour": { related:[], words:[
    ["red", "红色", "a red rose"],
    ["blue", "蓝色", "a blue sky"],
    ["green", "绿色", "green grass"],
    ["yellow", "黄色", "a yellow banana"],
    ["black", "黑色", "a black cat"],
    ["white", "白色", "white snow"],
    ["purple", "紫色", "a purple flower"],
    ["grey", "灰色", "grey clouds"],
  ]},
  "家人 family": { related:[], words:[
    ["mother", "母亲", "my mother"],
    ["father", "父亲", "my father"],
    ["brother", "兄弟", "an older brother"],
    ["sister", "姐妹", "a little sister"],
    ["son", "儿子", "their son"],
    ["daughter", "女儿", "their daughter"],
    ["uncle", "叔伯舅", "my uncle"],
    ["aunt", "姑姨婶", "my aunt"],
    ["cousin", "堂/表亲", "my cousin"],
  ]},
  "建筑 building": { related:["房子 house"], words:[
    ["school", "学校", "go to school"],
    ["hospital", "医院", "rush to hospital"],
    ["library", "图书馆", "study in the library"],
    ["museum", "博物馆", "visit a museum"],
    ["church", "教堂", "an old church"],
    ["bank", "银行", "go to the bank"],
    ["hotel", "酒店", "stay at a hotel"],
    ["factory", "工厂", "work in a factory"],
  ]},

  /* ============================================================
     IELTS 学术写作 / 阅读 高频辨析（注重语域与搭配）
     ============================================================ */
  "导致 cause": { related:["结果 consequence","因素 factor"], words:[
    ["cause", "导致（通用）；cause sth / cause sb to do", "cause pollution"],
    ["lead to", "导致、引起；后接名词", "lead to obesity"],
    ["result in", "造成、导致；后接名词", "result in delays"],
    ["trigger", "引发（突然、连锁反应）", "trigger a crisis"],
    ["bring about", "带来、引起（变化）", "bring about change"],
    ["give rise to", "引起（问题、现象，正式）", "give rise to concerns"],
    ["contribute to", "促成（众多原因之一）", "contribute to global warming"],
  ]},
  "结果 consequence": { related:["导致 cause"], words:[
    ["result", "结果（中性、直接）", "the result of the test"],
    ["consequence", "后果（多负面、间接）", "serious consequences"],
    ["outcome", "最终结果、结局", "the outcome of the talks"],
    ["effect", "影响、效果", "a positive effect"],
    ["repercussion", "（长期、不良）反响", "economic repercussions"],
    ["aftermath", "（灾难、事件的）余波", "the aftermath of the war"],
  ]},
  "影响（动）affect": { related:["影响（名）impact"], words:[
    ["affect", "影响（动词，最常用）", "Climate affects crops."],
    ["influence", "影响（潜移默化、逐渐）", "influence opinions"],
    ["impact", "强烈影响、冲击（on）", "impact on health"],
    ["shape", "塑造、根本性地影响", "shape society"],
    ["sway", "影响、左右（决定、看法）", "sway voters"],
  ]},
  "影响（名）impact": { related:["影响（动）affect"], words:[
    ["impact", "冲击、重大影响", "a huge impact"],
    ["effect", "影响、效果", "side effects"],
    ["influence", "影响力", "a strong influence"],
    ["implication", "潜在影响、含义", "policy implications"],
    ["ramification", "（复杂的）后果", "legal ramifications"],
  ]},
  "解决 solve": { related:["解决方案 solution"], words:[
    ["solve", "解决（问题、难题）", "solve a problem"],
    ["resolve", "解决（冲突、争端，正式）", "resolve a dispute"],
    ["address", "着手处理（问题、议题）", "address the issue"],
    ["tackle", "应对、攻克（主动）", "tackle poverty"],
    ["overcome", "克服（困难、障碍）", "overcome obstacles"],
    ["combat", "对抗、与…作斗争", "combat crime"],
  ]},
  "解决方案 solution": { related:["解决 solve"], words:[
    ["solution", "解决方案（solution to）", "a long-term solution"],
    ["remedy", "补救办法、疗法", "a remedy for the issue"],
    ["measure", "措施（take measures）", "take strict measures"],
    ["approach", "方法、途径", "a new approach"],
    ["answer", "解决办法（answer to）", "the answer to crime"],
  ]},
  "改善 improve": { related:["减轻 alleviate"], words:[
    ["improve", "改善、提高（通用）", "improve quality"],
    ["enhance", "增强、提升（质量、价值）", "enhance performance"],
    ["boost", "促进、提振（数量、信心）", "boost the economy"],
    ["upgrade", "升级、改进", "upgrade the system"],
    ["refine", "改进、完善（细节）", "refine the method"],
    ["optimize", "优化", "optimize resources"],
  ]},
  "减轻 alleviate": { related:["改善 improve"], words:[
    ["reduce", "减少（通用）", "reduce stress"],
    ["alleviate", "减轻、缓解（痛苦、问题，正式）", "alleviate poverty"],
    ["mitigate", "缓和、减轻（影响、风险，正式）", "mitigate the impact"],
    ["ease", "缓解、减轻", "ease the pain"],
    ["relieve", "减轻、缓解（疼痛、压力）", "relieve pressure"],
    ["lessen", "减少、减轻", "lessen the risk"],
  ]},
  "限制 limit": { related:["阻碍 hinder"], words:[
    ["limit", "限制（数量、程度）", "limit access"],
    ["restrict", "限制、约束（行动、自由）", "restrict movement"],
    ["curb", "抑制、遏制（增长、行为）", "curb inflation"],
    ["restrain", "克制、抑制", "restrain spending"],
    ["confine", "限制在…范围内", "confine to a region"],
    ["cap", "设上限", "cap the number"],
  ]},
  "阻碍 hinder": { related:["限制 limit","促进 promote"], words:[
    ["hinder", "阻碍、妨碍", "hinder progress"],
    ["hamper", "阻碍、束缚", "hamper development"],
    ["impede", "妨碍（正式）", "impede growth"],
    ["obstruct", "阻挡、阻塞", "obstruct the view"],
    ["prevent", "阻止（…发生）", "prevent disease"],
    ["inhibit", "抑制、阻碍", "inhibit learning"],
  ]},
  "促进 promote": { related:["阻碍 hinder"], words:[
    ["encourage", "鼓励、促进", "encourage participation"],
    ["promote", "促进、推动", "promote tourism"],
    ["foster", "培养、促进", "foster creativity"],
    ["stimulate", "刺激、激发", "stimulate demand"],
    ["facilitate", "促进、使便利", "facilitate communication"],
    ["spur", "激励、刺激", "spur growth"],
  ]},
  "需要 require": { related:[], words:[
    ["need", "需要（通用）", "need help"],
    ["require", "需要、要求（正式）", "require attention"],
    ["demand", "亟需、强烈需要", "demand effort"],
    ["necessitate", "使成为必要（正式）", "necessitate change"],
    ["call for", "需要、要求", "call for action"],
  ]},
  "包含 include": { related:[], words:[
    ["include", "包括（部分，非全部）", "include tax"],
    ["comprise", "由…组成（整体=各部分）", "comprise five units"],
    ["contain", "含有（内部成分）", "contain sugar"],
    ["encompass", "涵盖、包含（范围广）", "encompass many fields"],
    ["consist of", "由…构成（无被动）", "consist of three parts"],
    ["incorporate", "包含、纳入", "incorporate feedback"],
  ]},
  "表明 indicate": { related:["证据 evidence","强调 emphasize"], words:[
    ["show", "显示、表明（通用）", "show a trend"],
    ["indicate", "表明、暗示", "indicate a rise"],
    ["demonstrate", "证明、清楚显示", "demonstrate the effect"],
    ["reveal", "揭示、显露", "reveal the truth"],
    ["illustrate", "说明、举例说明", "illustrate the point"],
    ["reflect", "反映", "reflect a change"],
    ["suggest", "表明、暗示（不确定）", "data suggest that…"],
  ]},
  "强调 emphasize": { related:["表明 indicate"], words:[
    ["emphasize", "强调（通用）", "emphasize the need"],
    ["stress", "强调", "stress the importance"],
    ["highlight", "突出、强调", "highlight the risks"],
    ["underline", "强调、突显", "underline the point"],
    ["underscore", "强调（正式）", "underscore the value"],
    ["accentuate", "突出、使更明显", "accentuate differences"],
  ]},
  "主张 argue": { related:["观点 view"], words:[
    ["argue", "论证、主张（给理由）", "argue that…"],
    ["claim", "声称、宣称（未必属实）", "claim to be safe"],
    ["maintain", "坚持认为", "maintain that it works"],
    ["contend", "主张、争辩（正式）", "contend that…"],
    ["assert", "断言、坚称", "assert one's rights"],
    ["believe", "认为、相信", "believe it is true"],
    ["hold", "持（观点）", "hold the view that…"],
  ]},
  "观点 view": { related:["主张 argue"], words:[
    ["view", "观点、看法", "in my view"],
    ["opinion", "意见（个人主观）", "public opinion"],
    ["perspective", "视角、角度", "from a different perspective"],
    ["standpoint", "立场、观点", "from a moral standpoint"],
    ["attitude", "态度", "a positive attitude"],
    ["stance", "立场（正式）", "take a firm stance"],
  ]},
  "证据 evidence": { related:["表明 indicate"], words:[
    ["evidence", "证据（不可数）", "strong evidence"],
    ["proof", "确凿证明", "proof of identity"],
    ["data", "数据", "collect data"],
    ["statistics", "统计数据", "official statistics"],
    ["figures", "数字、数据", "recent figures"],
  ]},
  "预测 predict": { related:["评估 assess"], words:[
    ["predict", "预测、预言", "predict the result"],
    ["forecast", "预报（天气、经济）", "forecast growth"],
    ["estimate", "估计", "estimate the cost"],
    ["project", "预计、推算", "project future demand"],
    ["anticipate", "预期、预料", "anticipate problems"],
  ]},
  "评估 assess": { related:["预测 predict"], words:[
    ["assess", "评估", "assess the risk"],
    ["evaluate", "评价、评估", "evaluate the results"],
    ["measure", "衡量、测量", "measure success"],
    ["gauge", "判断、估量", "gauge opinion"],
    ["appraise", "评定、鉴定", "appraise the value"],
  ]},
  "因素 factor": { related:["导致 cause"], words:[
    ["factor", "因素", "a key factor"],
    ["element", "要素、成分", "a vital element"],
    ["aspect", "方面", "an important aspect"],
    ["component", "组成部分", "a major component"],
    ["cause", "起因", "the root cause"],
  ]},
  "好处 benefit": { related:["坏处 drawback"], words:[
    ["benefit", "好处、益处", "the benefits of exercise"],
    ["advantage", "优势", "a clear advantage"],
    ["merit", "优点、长处", "the merits of the plan"],
    ["upside", "好的一面", "the upside is…"],
    ["asset", "有利条件、财富", "a valuable asset"],
  ]},
  "坏处 drawback": { related:["好处 benefit"], words:[
    ["drawback", "缺点、不利之处", "the main drawback"],
    ["disadvantage", "劣势、不利条件", "at a disadvantage"],
    ["downside", "不利的一面", "the downside of fame"],
    ["shortcoming", "缺点、不足", "address shortcomings"],
    ["pitfall", "隐患、易犯的错", "avoid the pitfalls"],
  ]},
  "趋势 trend": { related:[], words:[
    ["trend", "趋势", "a growing trend"],
    ["tendency", "倾向", "a tendency to overeat"],
    ["pattern", "模式、规律", "a clear pattern"],
    ["inclination", "倾向（个人）", "an inclination to agree"],
  ]},
  "显著 significant": { related:[], words:[
    ["significant", "显著的、重大的", "a significant rise"],
    ["considerable", "相当大的", "considerable effort"],
    ["substantial", "大量的、可观的", "a substantial increase"],
    ["dramatic", "急剧的、显著的", "a dramatic fall"],
    ["marked", "明显的", "a marked improvement"],
    ["notable", "值得注意的", "a notable exception"],
  ]},
  "普遍 widespread": { related:[], words:[
    ["common", "常见的", "a common problem"],
    ["widespread", "广泛的、普遍的", "widespread use"],
    ["prevalent", "盛行的、普遍的", "prevalent in cities"],
    ["universal", "普遍的、全体的", "universal access"],
    ["pervasive", "无处不在的", "a pervasive influence"],
  ]},
  "明显 obvious": { related:[], words:[
    ["obvious", "明显的", "an obvious mistake"],
    ["clear", "清楚的", "a clear sign"],
    ["apparent", "显而易见的；表面上的", "for no apparent reason"],
    ["evident", "明显的（正式）", "It is evident that…"],
    ["conspicuous", "显眼的、惹人注目的", "conspicuous consumption"],
  ]},
  "复杂 complex": { related:[], words:[
    ["complex", "复杂的", "a complex system"],
    ["complicated", "复杂难懂的", "a complicated process"],
    ["sophisticated", "精密的、复杂的", "sophisticated technology"],
    ["intricate", "错综复杂的", "intricate details"],
    ["convoluted", "（过于）复杂费解的", "a convoluted argument"],
  ]},
  "充足 sufficient": { related:["缺乏 lack"], words:[
    ["enough", "足够的（通用）", "enough money"],
    ["sufficient", "充足的（较正式）", "sufficient evidence"],
    ["adequate", "足够的、适当的", "adequate supply"],
    ["ample", "充裕的", "ample opportunity"],
    ["plentiful", "大量的、丰富的", "plentiful resources"],
  ]},
  "缺乏 lack": { related:["充足 sufficient"], words:[
    ["lack", "缺乏（名/动）", "a lack of funding"],
    ["shortage", "短缺", "a water shortage"],
    ["scarcity", "稀缺", "scarcity of food"],
    ["deficiency", "不足、缺陷", "a vitamin deficiency"],
    ["absence", "缺乏、没有", "in the absence of"],
    ["dearth", "匮乏（正式）", "a dearth of talent"],
  ]},
  "稳定 stable": { related:[], words:[
    ["stable", "稳定的", "a stable economy"],
    ["steady", "平稳的、持续的", "a steady increase"],
    ["constant", "不变的、持续的", "a constant temperature"],
    ["consistent", "一致的、稳定的", "consistent results"],
    ["unchanged", "未变的", "remain unchanged"],
  ]},
  "占比 account for": { related:["比例 proportion"], words:[
    ["account for", "占（比例）", "account for 30%"],
    ["make up", "构成、占", "make up half"],
    ["constitute", "构成、占（正式）", "constitute a majority"],
    ["represent", "代表、占", "represent a fifth"],
    ["comprise", "占、构成", "comprise 40%"],
  ]},
  "比例 proportion": { related:["占比 account for"], words:[
    ["proportion", "比例、部分", "a large proportion"],
    ["percentage", "百分比", "a high percentage"],
    ["rate", "比率、速率", "the birth rate"],
    ["ratio", "比率（A:B）", "a ratio of 2:1"],
    ["share", "份额", "a market share"],
    ["fraction", "小部分", "a fraction of the cost"],
  ]},
  "主要 main": { related:["重要 important"], words:[
    ["main", "主要的", "the main reason"],
    ["major", "主要的、重大的", "a major factor"],
    ["primary", "首要的", "the primary goal"],
    ["principal", "最重要的（正式）", "the principal cause"],
    ["chief", "首要的", "the chief concern"],
    ["leading", "领先的、主要的", "a leading cause"],
  ]},
  "各种 various": { related:[], words:[
    ["various", "各种各样的", "various reasons"],
    ["diverse", "多样的", "a diverse range"],
    ["varied", "各不相同的", "a varied diet"],
    ["numerous", "众多的", "numerous examples"],
    ["an array of", "一系列、大量", "an array of options"],
  ]},
  "方法 method": { related:["解决方案 solution"], words:[
    ["method", "方法（系统、有步骤）", "a teaching method"],
    ["approach", "方式、思路（approach to）", "an approach to learning"],
    ["means", "手段（a means of）", "a means of transport"],
    ["technique", "技巧", "a relaxation technique"],
    ["strategy", "策略", "a marketing strategy"],
    ["way", "方式（通用）", "a way to improve"],
  ]},
  "目的 aim": { related:[], words:[
    ["aim", "目标、目的（总体意图）", "the aim of the study"],
    ["goal", "长远目标", "a life goal"],
    ["objective", "具体、可衡量的目标", "clear objectives"],
    ["purpose", "目的、用途", "the purpose of the law"],
    ["target", "（数字）指标", "a sales target"],
  ]},

  /* ---------- 动作：第三批 ---------- */
  "等 wait": { related:[], words:[
    ["wait", "等待（通用，wait for）", "wait for the bus"],
    ["await", "等候（正式，及物）", "await a reply"],
    ["expect", "预期、等着（会来）", "expect a guest"],
    ["queue", "排队（英式）", "queue up"],
    ["linger", "逗留、徘徊", "linger after class"],
  ]},
  "比较 compare": { related:[], words:[
    ["compare", "比较（compare with/to）", "compare prices"],
    ["contrast", "对比（强调差异）", "contrast the two"],
    ["differ", "不同、相异", "opinions differ"],
    ["resemble", "相似、像", "resemble her mother"],
    ["match", "相配、匹配", "match the colours"],
  ]},
  "连接 connect": { related:["分开 separate"], words:[
    ["connect", "连接（通用）", "connect two wires"],
    ["link", "联系、链接", "link the ideas"],
    ["join", "连接、加入", "join the pipes"],
    ["attach", "附上、贴上", "attach a file"],
    ["combine", "结合、合并", "combine forces"],
    ["unite", "联合、团结", "unite the team"],
  ]},
  "分开 separate": { related:["连接 connect"], words:[
    ["separate", "分开、隔开（通用）", "separate the rubbish"],
    ["divide", "划分、分割", "divide into groups"],
    ["split", "分裂、劈开", "split the bill"],
    ["detach", "拆下、分离", "detach the label"],
    ["part", "分别、分开", "part the curtains"],
  ]},
  "混合 mix": { related:["做饭 cook"], words:[
    ["mix", "混合（通用）", "mix the colours"],
    ["blend", "调和、混合（均匀）", "blend the fruit"],
    ["combine", "结合", "combine the ingredients"],
    ["stir", "搅拌", "stir the soup"],
    ["merge", "合并（公司、事物）", "merge two companies"],
  ]},
  "收集 collect": { related:[], words:[
    ["collect", "收集、采集（通用）", "collect stamps"],
    ["gather", "聚集、采集", "gather information"],
    ["accumulate", "积累、积聚", "accumulate wealth"],
    ["assemble", "集合、装配", "assemble a crowd"],
    ["compile", "汇编、编纂", "compile a list"],
  ]},
  "分发 distribute": { related:["给 give"], words:[
    ["distribute", "分发、分配（通用）", "distribute leaflets"],
    ["share", "分享、分摊", "share the food"],
    ["allocate", "分配（资源、资金）", "allocate funds"],
    ["spread", "散布、传播", "spread the news"],
    ["hand out", "分发、发放", "hand out forms"],
  ]},
  "储存 store": { related:[], words:[
    ["store", "储存、存放（通用）", "store data"],
    ["keep", "保留、保存", "keep the receipt"],
    ["preserve", "保存、保护（不变质）", "preserve food"],
    ["stock", "储备、备货", "stock the shelves"],
    ["reserve", "预留、储备", "reserve a seat"],
  ]},
  "旋转 turn": { related:[], words:[
    ["turn", "转动、转向（通用）", "turn the key"],
    ["rotate", "旋转（绕轴）", "rotate the wheel"],
    ["spin", "快速旋转、纺", "spin around"],
    ["twist", "扭、拧", "twist the cap"],
    ["swirl", "打旋、回旋", "swirl the wine"],
  ]},
  "摇 / 抖 shake": { related:[], words:[
    ["shake", "摇动、抖动（通用）", "shake the bottle"],
    ["tremble", "（因恐惧/虚弱）发抖", "tremble with fear"],
    ["shiver", "（因冷）打哆嗦", "shiver in the cold"],
    ["quiver", "（轻微）颤动", "lips quivering"],
    ["vibrate", "振动（机械、声音）", "The phone vibrates."],
  ]},
  "推迟 delay": { related:["取消 cancel"], words:[
    ["delay", "推迟、耽搁（通用）", "delay the flight"],
    ["postpone", "延期、推迟（计划）", "postpone the meeting"],
    ["defer", "延期、推迟（正式）", "defer payment"],
    ["put off", "拖延、推迟（口语）", "put off the task"],
  ]},
  "取消 cancel": { related:["推迟 delay"], words:[
    ["cancel", "取消（通用）", "cancel the order"],
    ["abolish", "废除（制度、法律）", "abolish slavery"],
    ["scrap", "废弃、取消（计划）", "scrap the plan"],
    ["call off", "取消（活动）", "call off the game"],
  ]},
  "重复 repeat": { related:[], words:[
    ["repeat", "重复（通用）", "repeat the word"],
    ["reiterate", "重申（正式）", "reiterate the point"],
    ["echo", "回响、附和", "echo his views"],
    ["duplicate", "复制、重复", "duplicate the file"],
  ]},
  "警告 warn": { related:[], words:[
    ["warn", "警告、提醒", "warn of danger"],
    ["caution", "告诫、提醒", "caution against haste"],
    ["alert", "使警觉、警示", "alert the police"],
    ["notify", "通知（正式）", "notify the staff"],
    ["inform", "告知", "inform customers"],
  ]},
  "抱怨 complain": { related:["反对 oppose"], words:[
    ["complain", "抱怨、投诉（通用）", "complain about noise"],
    ["grumble", "嘟囔、发牢骚", "grumble about work"],
    ["moan", "抱怨、哼唧", "moan about the weather"],
    ["protest", "抗议（公开）", "protest against the law"],
    ["object", "反对、提出异议", "object to the plan"],
  ]},
  "同意 agree": { related:["反对 oppose"], words:[
    ["agree", "同意、赞成（通用）", "agree with you"],
    ["consent", "同意、答应（正式）", "consent to the deal"],
    ["approve", "批准、赞成", "approve the request"],
    ["accept", "接受", "accept the offer"],
  ]},
  "反对 oppose": { related:["同意 agree","抱怨 complain"], words:[
    ["oppose", "反对（通用）", "oppose the plan"],
    ["disagree", "不同意", "disagree with him"],
    ["object", "反对、提异议", "object to the rule"],
    ["resist", "抵制、抗拒", "resist change"],
    ["reject", "拒绝、否决", "reject the idea"],
  ]},
  "拥有 own": { related:[], words:[
    ["own", "拥有（通用）", "own a house"],
    ["possess", "拥有、具有（正式）", "possess skills"],
    ["have", "有（最通用）", "have a car"],
    ["belong", "属于（belong to）", "It belongs to me."],
  ]},
  "命令 order": { related:[], words:[
    ["order", "命令、下令（通用）", "order them to stop"],
    ["command", "指挥、命令", "command an army"],
    ["direct", "指示、指挥", "direct the workers"],
    ["instruct", "指导、吩咐", "instruct staff to wait"],
  ]},
  "数 / 算 count": { related:[], words:[
    ["count", "数、计数", "count the votes"],
    ["calculate", "计算（数学）", "calculate the total"],
    ["compute", "计算（正式/电脑）", "compute the average"],
    ["add", "相加、加上", "add the numbers"],
    ["measure", "测量", "measure the length"],
  ]},
  "庆祝 celebrate": { related:[], words:[
    ["celebrate", "庆祝（通用）", "celebrate a birthday"],
    ["commemorate", "纪念（庄重）", "commemorate the heroes"],
    ["honour", "颂扬、纪念", "honour the dead"],
    ["mark", "标志性地纪念", "mark the occasion"],
  ]},

  /* ---------- 形容词：尺寸 / 性质 / 味道 ---------- */
  "高 tall / high": { related:[], words:[
    ["tall", "（人/物）高的", "a tall man"],
    ["high", "（高度/位置）高的", "a high mountain"],
    ["towering", "高耸的", "towering skyscrapers"],
    ["lofty", "高耸的；崇高的", "lofty peaks"],
  ]},
  "长 long": { related:[], words:[
    ["long", "长的（通用）", "a long road"],
    ["lengthy", "冗长的", "a lengthy speech"],
    ["extended", "延长的、扩展的", "an extended stay"],
    ["prolonged", "持续过久的", "prolonged drought"],
  ]},
  "宽 / 窄 wide": { related:[], words:[
    ["wide", "宽的（通用）", "a wide road"],
    ["broad", "宽阔的", "broad shoulders"],
    ["spacious", "宽敞的", "a spacious room"],
    ["narrow", "窄的", "a narrow lane"],
  ]},
  "深 / 浅 deep": { related:[], words:[
    ["deep", "深的（通用）", "deep water"],
    ["shallow", "浅的；肤浅的", "a shallow pool"],
    ["profound", "深刻的、深远的", "a profound impact"],
  ]},
  "重 / 轻 heavy": { related:[], words:[
    ["heavy", "重的（通用）", "a heavy bag"],
    ["light", "轻的", "as light as a feather"],
    ["hefty", "沉重的、大的", "a hefty box"],
    ["weighty", "沉重的；重大的", "a weighty issue"],
  ]},
  "软 / 硬 soft": { related:[], words:[
    ["soft", "软的（通用）", "a soft pillow"],
    ["hard", "硬的；难的", "a hard surface"],
    ["tender", "柔嫩的、温柔的", "tender meat"],
    ["firm", "结实的、坚定的", "a firm mattress"],
  ]},
  "光滑 / 粗糙 smooth": { related:[], words:[
    ["smooth", "光滑的、平稳的", "smooth skin"],
    ["rough", "粗糙的；大致的", "rough hands"],
    ["sleek", "光亮平滑的", "a sleek design"],
    ["coarse", "粗糙的、粗的", "coarse sand"],
  ]},
  "亮 / 暗 bright": { related:[], words:[
    ["bright", "明亮的、鲜艳的", "a bright light"],
    ["dark", "黑暗的、深色的", "a dark room"],
    ["dim", "昏暗的、微弱的", "dim lighting"],
    ["dull", "暗淡的；乏味的", "dull colours"],
  ]},
  "满 / 空 full": { related:[], words:[
    ["full", "满的（通用）", "a full glass"],
    ["empty", "空的", "an empty box"],
    ["packed", "挤满的、塞满的", "a packed train"],
    ["vacant", "空着的（座位、房间）", "a vacant seat"],
  ]},
  "味道 taste": { related:["吃 eat"], words:[
    ["sweet", "甜的", "sweet candy"],
    ["sour", "酸的", "sour lemon"],
    ["bitter", "苦的", "bitter coffee"],
    ["spicy", "辣的", "spicy food"],
    ["salty", "咸的", "salty chips"],
    ["bland", "清淡无味的", "bland soup"],
  ]},

  /* ---------- 词族：食物 / 生物 / 物品 ---------- */
  "蔬菜 vegetable": { related:["食物 food"], words:[
    ["potato", "土豆", "mashed potato"],
    ["tomato", "番茄", "a ripe tomato"],
    ["carrot", "胡萝卜", "grate a carrot"],
    ["onion", "洋葱", "chop an onion"],
    ["cabbage", "卷心菜", "a head of cabbage"],
    ["pepper", "辣椒/甜椒", "a green pepper"],
    ["cucumber", "黄瓜", "sliced cucumber"],
  ]},
  "饮料 drinks": { related:["喝 drink"], words:[
    ["water", "水", "a glass of water"],
    ["juice", "果汁", "orange juice"],
    ["coffee", "咖啡", "black coffee"],
    ["tea", "茶", "a cup of tea"],
    ["milk", "牛奶", "fresh milk"],
    ["soda", "汽水", "a can of soda"],
    ["wine", "葡萄酒", "red wine"],
  ]},
  "鸟 bird": { related:["动物 animal"], words:[
    ["sparrow", "麻雀", "a little sparrow"],
    ["eagle", "鹰", "a soaring eagle"],
    ["owl", "猫头鹰", "a wise owl"],
    ["parrot", "鹦鹉", "a talking parrot"],
    ["pigeon", "鸽子", "feed the pigeons"],
    ["swan", "天鹅", "a white swan"],
    ["penguin", "企鹅", "a waddling penguin"],
  ]},
  "昆虫 insect": { related:["动物 animal"], words:[
    ["bee", "蜜蜂", "a busy bee"],
    ["ant", "蚂蚁", "a line of ants"],
    ["fly", "苍蝇", "swat a fly"],
    ["mosquito", "蚊子", "a mosquito bite"],
    ["butterfly", "蝴蝶", "a colourful butterfly"],
    ["spider", "蜘蛛", "a spider's web"],
    ["beetle", "甲虫", "a black beetle"],
  ]},
  "海洋动物 sea creature": { related:["动物 animal"], words:[
    ["fish", "鱼", "catch a fish"],
    ["shark", "鲨鱼", "a great white shark"],
    ["whale", "鲸", "a blue whale"],
    ["dolphin", "海豚", "a playful dolphin"],
    ["crab", "螃蟹", "a hermit crab"],
    ["octopus", "章鱼", "an eight-armed octopus"],
    ["jellyfish", "水母", "a stinging jellyfish"],
  ]},
  "器官 organ": { related:["身体 body"], words:[
    ["heart", "心脏", "a beating heart"],
    ["lung", "肺", "healthy lungs"],
    ["liver", "肝", "the liver"],
    ["stomach", "胃", "an empty stomach"],
    ["brain", "大脑", "the human brain"],
    ["kidney", "肾", "two kidneys"],
  ]},
  "配饰 accessory": { related:["衣服 clothes"], words:[
    ["hat", "帽子", "a straw hat"],
    ["scarf", "围巾", "a wool scarf"],
    ["glove", "手套", "leather gloves"],
    ["belt", "腰带", "a leather belt"],
    ["tie", "领带", "wear a tie"],
    ["sock", "袜子", "a pair of socks"],
    ["watch", "手表", "a wrist watch"],
  ]},
  "厨房电器 appliance": { related:["做饭 cook","容器 cup"], words:[
    ["fridge", "冰箱", "open the fridge"],
    ["oven", "烤箱", "preheat the oven"],
    ["microwave", "微波炉", "heat it in the microwave"],
    ["stove", "炉灶", "a gas stove"],
    ["blender", "搅拌机", "use a blender"],
    ["toaster", "烤面包机", "pop-up toaster"],
    ["kettle", "烧水壶", "boil the kettle"],
  ]},
  "工具 tool": { related:["修 fix"], words:[
    ["hammer", "锤子", "a claw hammer"],
    ["screwdriver", "螺丝刀", "a flat screwdriver"],
    ["saw", "锯", "an electric saw"],
    ["drill", "电钻", "a power drill"],
    ["wrench", "扳手", "tighten with a wrench"],
    ["nail", "钉子", "hammer a nail"],
    ["axe", "斧头", "chop with an axe"],
  ]},
  "学科 subject": { related:[], words:[
    ["maths", "数学", "good at maths"],
    ["science", "科学", "a science class"],
    ["history", "历史", "study history"],
    ["geography", "地理", "world geography"],
    ["biology", "生物", "biology lab"],
    ["chemistry", "化学", "chemistry experiment"],
    ["art", "美术", "an art lesson"],
  ]},
  "自然景观 landscape": { related:["植物 plant"], words:[
    ["mountain", "山", "climb a mountain"],
    ["river", "河", "a flowing river"],
    ["lake", "湖", "a calm lake"],
    ["forest", "森林", "a dense forest"],
    ["desert", "沙漠", "a vast desert"],
    ["valley", "山谷", "a green valley"],
    ["hill", "小山、丘陵", "roll down a hill"],
    ["beach", "海滩", "a sandy beach"],
  ]},
  "太空 space": { related:[], words:[
    ["sun", "太阳", "the rising sun"],
    ["moon", "月亮", "a full moon"],
    ["star", "星星", "a bright star"],
    ["planet", "行星", "the planet Mars"],
    ["earth", "地球", "planet Earth"],
    ["galaxy", "星系", "a distant galaxy"],
    ["comet", "彗星", "a passing comet"],
  ]},
  "方向 direction": { related:[], words:[
    ["north", "北", "head north"],
    ["south", "南", "fly south"],
    ["east", "东", "the east coast"],
    ["west", "西", "the west wing"],
    ["left", "左", "turn left"],
    ["right", "右", "on the right"],
  ]},

};
