/* ============================================================
   英语单词联想网络  —  你只需要编辑这个文件就能加词！
   ------------------------------------------------------------
   思路：按「意思」联想，而不是按词性。每个概念是一个中心，
        相关的词挂在周围。同一个词出现在多个概念里时，
        它会自动变成连接两团的「桥」（比如 gulp 连「吃」和「喝」）。

   结构：
     "概念名（中文 英文）": {
       related: ["可关联到的其它概念名", ...],   // 可留空 []
       words: [
         ["word", "中文释义；和近义词的区别", "例句（可留空 '')"],
         ...
       ]
     },

   想加新词？复制一段改成你的内容即可。注意：
   - 所有引号用英文 ""，逗号用英文 ,
   - 想让两个词产生联系，只要把它们放进同一个概念，或在 related 里互相写上对方
   - 同名词写在不同概念里 = 自动桥接，不会重复
   ============================================================ */

const DATA = {

  /* ---------- 动作：吃喝 ---------- */
  "吃 eat": { related:["喝 drink","嘴 mouth","食物 food","做饭 cook"], words:[
    ["eat", "吃（通用）", "eat lunch"],
    ["swallow", "吞咽：不嚼直接咽下去", "swallow a pill"],
    ["chew", "咀嚼：用牙磨碎", "chew gum"],
    ["bite", "咬：用牙咬住或咬下一口", "bite an apple"],
    ["gnaw", "啃：持续地咬硬物", "a dog gnawing a bone"],
    ["nibble", "小口啃、一点点咬", "nibble on a biscuit"],
    ["munch", "大声咀嚼、嚼得有声", "munch crisps"],
    ["devour", "狼吞虎咽、吃光", "devour a whole pizza"],
    ["lick", "舔", "lick an ice cream"],
    ["taste", "品尝、尝味道", "taste the soup"],
    ["gulp", "大口吞食", "gulp down food"],
  ]},
  "喝 drink": { related:["吃 eat","容器 cup"], words:[
    ["drink", "喝（通用）", "drink water"],
    ["sip", "小口抿、慢慢喝", "sip hot tea"],
    ["gulp", "大口吞咽（咕咚一下）", "gulp down a glass of water"],
    ["swallow", "咽下去", "hard to swallow"],
    ["slurp", "出声地吸食、唏哩呼噜喝", "slurp noodles"],
    ["taste", "品尝（饮品也用）", "taste the wine"],
  ]},

  /* ---------- 动作：移动 / 感官 ---------- */
  "移动 / 走 move": { related:["路 road","快 fast"], words:[
    ["walk", "走、步行", "walk to school"],
    ["run", "跑", "run fast"],
    ["jog", "慢跑（健身）", "jog in the park"],
    ["sprint", "短距离冲刺、全力跑", "sprint to the finish"],
    ["stroll", "悠闲地散步", "stroll along the beach"],
    ["wander", "漫步、闲逛（无目的）", "wander around town"],
    ["march", "齐步走、行军", "soldiers marching"],
    ["hike", "徒步、远足", "hike up a mountain"],
    ["crawl", "爬行", "a baby crawling"],
    ["limp", "一瘸一拐地走", "limp after the injury"],
    ["stride", "大步走", "stride confidently"],
    ["climb", "攀爬", "climb a ladder"],
  ]},
  "看 look": { related:["眼睛 eye"], words:[
    ["look", "（主动）看，强调动作", "look at the board"],
    ["see", "看见，强调结果", "I can see the sea."],
    ["watch", "观看会动的东西", "watch a film"],
    ["stare", "盯着看（久、专注）", "stare at the screen"],
    ["glare", "怒视、瞪", "glare angrily"],
    ["glance", "瞥一眼（快、短）", "glance at the clock"],
    ["gaze", "凝视（出神、欣赏）", "gaze at the stars"],
    ["peep", "偷看、窥视", "peep through the keyhole"],
    ["glimpse", "瞥见、一瞥（名/动）", "catch a glimpse of"],
    ["observe", "观察（仔细研究）", "observe behaviour"],
  ]},
  "说 speak": { related:["嘴 mouth"], words:[
    ["say", "说（后接内容）", "say sorry"],
    ["tell", "告诉（后接人）", "tell me a story"],
    ["speak", "讲（语言/正式发言）", "speak French"],
    ["talk", "交谈、聊（双向）", "talk to a friend"],
    ["whisper", "低语、耳语", "whisper a secret"],
    ["shout", "喊、大声叫", "shout for help"],
    ["yell", "吼叫（更激动）", "yell in anger"],
    ["scream", "尖叫", "scream in fear"],
    ["mutter", "嘀咕、小声抱怨", "mutter under one's breath"],
    ["mumble", "含糊不清地说", "mumble an answer"],
    ["argue", "争论、争辩", "argue about money"],
  ]},

  /* ---------- 动作：表情 / 情绪反应 ---------- */
  "笑 laugh": { related:[], words:[
    ["laugh", "（出声）笑", "laugh out loud"],
    ["smile", "微笑（不出声）", "smile at someone"],
    ["giggle", "咯咯地笑、傻笑", "giggle nervously"],
    ["grin", "咧嘴大笑", "grin with joy"],
    ["chuckle", "轻声笑、暗笑", "chuckle quietly"],
    ["smirk", "得意/嘲讽地笑", "smirk smugly"],
    ["beam", "笑容满面", "beam with pride"],
  ]},
  "哭 cry": { related:[], words:[
    ["cry", "哭（通用）", "cry loudly"],
    ["weep", "（默默）流泪、哭泣", "weep for joy"],
    ["sob", "抽泣、啜泣", "sob uncontrollably"],
    ["whimper", "呜咽、低声哭", "whimper in pain"],
    ["wail", "嚎啕大哭、哀号", "wail in grief"],
  ]},

  /* ---------- 动作：手部 ---------- */
  "拿 / 握 hold": { related:["扔 throw","推拉 push / pull","给 give"], words:[
    ["hold", "拿着、握住、抱", "hold a cup"],
    ["grab", "抓住（突然、快）", "grab my hand"],
    ["grasp", "紧紧抓住、握牢", "grasp the rope"],
    ["grip", "（用力）握紧", "grip the wheel"],
    ["clutch", "（紧张地）抱紧、攥住", "clutch a bag"],
    ["seize", "夺取、抓住（机会/物）", "seize the chance"],
    ["snatch", "一把夺过、抢", "snatch the phone"],
    ["hug", "拥抱", "hug a friend"],
    ["carry", "搬运、携带（拿着移动）", "carry a bag"],
    ["lift", "举起、抬", "lift a box"],
  ]},
  "扔 throw": { related:["拿 / 握 hold"], words:[
    ["throw", "扔、投（通用）", "throw a ball"],
    ["toss", "轻轻抛、随手扔", "toss a coin"],
    ["hurl", "猛力投掷", "hurl a rock"],
    ["fling", "（用力、随意）甩出", "fling the door open"],
    ["cast", "投、撒（网/钓线，正式）", "cast a net"],
  ]},
  "打 hit": { related:["破坏 break"], words:[
    ["hit", "打、击中（通用）", "hit the target"],
    ["strike", "击打（正式/突然）", "strike a match"],
    ["slap", "扇、掌掴", "slap his face"],
    ["punch", "（用拳）猛击", "punch the bag"],
    ["beat", "（反复）打、揍", "beat a drum"],
    ["knock", "敲（门）", "knock on the door"],
    ["tap", "轻拍、轻敲", "tap on the shoulder"],
    ["smash", "猛砸、砸碎", "smash a window"],
  ]},
  "推拉 push / pull": { related:["拿 / 握 hold"], words:[
    ["push", "推", "push the door"],
    ["pull", "拉", "pull the rope"],
    ["drag", "拖、拽（费力地）", "drag a heavy box"],
    ["shove", "猛推、粗暴地推", "shove someone aside"],
    ["tug", "用力拉一下、拽", "tug at her sleeve"],
    ["lift", "举起、抬", "lift weights"],
    ["carry", "搬运、携带", "carry a bag"],
  ]},
  "切 cut": { related:["做饭 cook"], words:[
    ["cut", "切、割（通用）", "cut the cake"],
    ["slice", "切片", "slice bread"],
    ["chop", "剁、砍（用力、成块）", "chop vegetables"],
    ["carve", "雕刻、切（肉）", "carve a turkey"],
    ["trim", "修剪", "trim the hedge"],
    ["peel", "削皮", "peel an apple"],
    ["mince", "切碎、绞碎", "minced meat"],
  ]},

  /* ---------- 动作：头脑 / 休息 ---------- */
  "想 think": { related:[], words:[
    ["think", "想、认为（通用）", "think hard"],
    ["consider", "考虑（经思量）", "consider the options"],
    ["ponder", "沉思、深思", "ponder a question"],
    ["reflect", "反思、回想", "reflect on the past"],
    ["wonder", "想知道、纳闷", "wonder what happened"],
    ["imagine", "想象", "imagine a perfect day"],
    ["guess", "猜测", "guess the answer"],
    ["doubt", "怀疑", "doubt the news"],
  ]},
  "睡 sleep": { related:["累 tired"], words:[
    ["sleep", "睡觉（通用）", "sleep eight hours"],
    ["nap", "小睡、打盹", "take a nap"],
    ["doze", "打瞌睡（不知不觉）", "doze off"],
    ["slumber", "酣睡（文学）", "deep slumber"],
    ["rest", "休息", "rest for a while"],
    ["yawn", "打哈欠", "yawn sleepily"],
  ]},

  /* ---------- 动作：更多 ---------- */
  "给 give": { related:["拿 / 握 hold"], words:[
    ["give", "给（通用）", "give a gift"],
    ["offer", "（主动）提供、提议", "offer help"],
    ["provide", "提供（正式），provide sb with", "provide food"],
    ["hand", "递给（手递手）", "hand me the salt"],
    ["present", "赠予、颁发（正式）", "present an award"],
    ["donate", "捐赠", "donate money to charity"],
    ["deliver", "递送、配送", "deliver a parcel"],
    ["supply", "供应（持续、批量）", "supply electricity"],
  ]},
  "做 / 造 make": { related:[], words:[
    ["make", "做、制作（通用）", "make a cake"],
    ["do", "做、从事（动作/事务）", "do homework"],
    ["create", "创造、创作", "create art"],
    ["build", "建造、搭建", "build a house"],
    ["produce", "生产、制造", "produce cars"],
    ["construct", "建造（正式、大型）", "construct a bridge"],
    ["manufacture", "（工厂）批量制造", "manufacture goods"],
  ]},
  "帮助 help": { related:[], words:[
    ["help", "帮助（通用）", "help a friend"],
    ["assist", "协助（正式）", "assist the manager"],
    ["aid", "援助（多指物资/正式）", "aid the victims"],
    ["support", "支持、扶持", "support a cause"],
    ["back", "支持、力挺", "back the plan"],
  ]},
  "开始 start": { related:["结束 finish"], words:[
    ["start", "开始（通用）", "start work"],
    ["begin", "开始（稍正式）", "begin a journey"],
    ["commence", "开始（很正式、书面）", "commence proceedings"],
    ["launch", "发起、推出、发射", "launch a product"],
    ["initiate", "发起、启动（正式）", "initiate a project"],
  ]},
  "结束 finish": { related:["开始 start"], words:[
    ["finish", "完成、结束（通用）", "finish dinner"],
    ["end", "结束、终结", "end a war"],
    ["complete", "完成（达到完整）", "complete the form"],
    ["stop", "停止", "stop talking"],
    ["cease", "停止（正式）", "cease fire"],
    ["conclude", "结束、总结（正式）", "conclude the speech"],
  ]},
  "增加 increase": { related:["减少 reduce"], words:[
    ["increase", "增加（通用）", "increase production"],
    ["rise", "上升（不及物，不接宾语）", "Prices rise."],
    ["raise", "提高（及物，接宾语）", "raise prices"],
    ["grow", "增长（自然、逐渐）", "The economy grows."],
    ["expand", "扩张、扩大", "expand the business"],
    ["boost", "促进、提升", "boost sales"],
    ["soar", "猛涨、剧增", "Prices soared."],
  ]},
  "减少 reduce": { related:["增加 increase"], words:[
    ["reduce", "减少（主动降低）", "reduce costs"],
    ["decrease", "减少（数量下降，正式）", "Sales decreased."],
    ["decline", "下降、衰退（渐、常负面）", "Population declines."],
    ["drop", "（突然）下降、下跌", "Temperatures dropped."],
    ["diminish", "削弱、减小（重要性）", "diminish its value"],
    ["shrink", "缩小、收缩", "The market shrank."],
  ]},
  "改变 change": { related:[], words:[
    ["change", "改变（通用）", "change your mind"],
    ["alter", "（部分、细节）更改", "alter a dress"],
    ["modify", "（小幅）修改、调整", "modify the design"],
    ["transform", "（彻底）改变、变形", "transform the city"],
    ["adjust", "调整、调节", "adjust the volume"],
    ["convert", "转换、改装", "convert dollars to euros"],
  ]},
  "学习 learn": { related:["教 teach"], words:[
    ["learn", "学会、掌握（结果）", "learn English"],
    ["study", "学习、钻研（过程）", "study hard"],
    ["master", "精通", "master a skill"],
    ["revise", "复习（英式）", "revise for exams"],
    ["memorize", "背诵、记住", "memorize a poem"],
    ["practise", "练习（英式拼写）", "practise the piano"],
  ]},
  "教 teach": { related:["学习 learn"], words:[
    ["teach", "教（通用）", "teach maths"],
    ["instruct", "指导、传授（正式）", "instruct students"],
    ["train", "培训、训练", "train new staff"],
    ["educate", "教育", "educate children"],
    ["coach", "辅导、教练", "coach a team"],
    ["tutor", "（一对一）辅导", "tutor a student"],
  ]},
  "找 find": { related:[], words:[
    ["find", "找到（通用）", "find the keys"],
    ["discover", "发现（已存在的）", "discover a cave"],
    ["locate", "定位、找到（确切位置）", "locate the fault"],
    ["detect", "察觉、探测", "detect a leak"],
    ["search", "搜寻（动作，search for）", "search for clues"],
    ["seek", "寻求（正式）", "seek advice"],
  ]},
  "买卖 buy / sell": { related:["钱 money"], words:[
    ["buy", "买（通用）", "buy a ticket"],
    ["purchase", "购买（正式）", "purchase goods"],
    ["sell", "卖", "sell a car"],
    ["trade", "交易、买卖", "trade stocks"],
    ["bargain", "讨价还价", "bargain over the price"],
    ["afford", "买得起、负担得起", "can't afford it"],
  ]},
  "做饭 cook": { related:["吃 eat","食物 food","切 cut"], words:[
    ["cook", "做饭、烹饪（通用）", "cook dinner"],
    ["boil", "煮、煮沸", "boil an egg"],
    ["fry", "煎、炒、炸", "fry an egg"],
    ["bake", "烘焙（烤箱、面点）", "bake bread"],
    ["roast", "烤（肉、整块）", "roast a chicken"],
    ["grill", "炙烤、烧烤", "grill steak"],
    ["steam", "蒸", "steam vegetables"],
  ]},
  "清洁 clean": { related:[], words:[
    ["clean", "打扫、弄干净（通用）", "clean the room"],
    ["wash", "洗", "wash your hands"],
    ["wipe", "擦（用布/纸）", "wipe the table"],
    ["scrub", "用力擦洗、刷", "scrub the floor"],
    ["rinse", "冲洗、漂洗", "rinse the cup"],
    ["sweep", "扫", "sweep the floor"],
    ["mop", "拖（地）", "mop the kitchen"],
  ]},
  "破坏 break": { related:["修 fix","打 hit"], words:[
    ["break", "弄坏、打破（通用）", "break a glass"],
    ["smash", "猛砸、砸碎", "smash a window"],
    ["crack", "（出现裂纹）裂开", "The cup cracked."],
    ["shatter", "（碎成片）粉碎", "The mirror shattered."],
    ["destroy", "彻底摧毁", "destroy the building"],
    ["ruin", "毁掉、糟蹋", "ruin the party"],
  ]},
  "修 fix": { related:["破坏 break"], words:[
    ["fix", "修理（通用、口语）", "fix the car"],
    ["repair", "修理（较正式）", "repair the roof"],
    ["mend", "修补（衣物、小物）", "mend a sock"],
    ["restore", "修复、还原（旧物）", "restore a painting"],
  ]},
  "触摸 touch": { related:[], words:[
    ["touch", "触摸、碰（通用）", "touch the screen"],
    ["feel", "（用手）感觉、摸", "feel the fabric"],
    ["stroke", "抚摸（轻、来回）", "stroke a cat"],
    ["pat", "轻拍", "pat the dog"],
    ["rub", "揉、摩擦", "rub your eyes"],
    ["scratch", "挠、抓", "scratch an itch"],
  ]},
  "掉落 fall": { related:[], words:[
    ["fall", "落下、跌倒（通用）", "fall down"],
    ["drop", "掉落（物从手中）", "drop a plate"],
    ["collapse", "倒塌、坍塌", "The roof collapsed."],
    ["tumble", "滚落、摔倒", "tumble down the stairs"],
    ["slip", "滑倒、打滑", "slip on the ice"],
    ["trip", "绊倒、绊一下", "trip over a wire"],
  ]},

  /* ---------- 情绪（形容词）---------- */
  "高兴 happy": { related:["难过 sad","兴奋 excited"], words:[
    ["happy", "高兴、幸福（通用）", "a happy child"],
    ["glad", "（一时）高兴的", "glad to see you"],
    ["pleased", "满意、欣慰", "pleased with the result"],
    ["delighted", "非常高兴（语气强）", "delighted to help"],
    ["cheerful", "开朗、兴高采烈", "a cheerful mood"],
    ["joyful", "充满喜悦", "a joyful celebration"],
    ["thrilled", "激动、兴奋极了", "thrilled about the trip"],
    ["content", "知足、满足", "content with life"],
  ]},
  "难过 sad": { related:["高兴 happy"], words:[
    ["sad", "难过、伤心（通用）", "feel sad"],
    ["unhappy", "不开心的", "an unhappy marriage"],
    ["upset", "心烦、难受", "upset about the news"],
    ["gloomy", "忧郁、阴沉", "a gloomy mood"],
    ["miserable", "痛苦、悲惨", "feel miserable"],
    ["depressed", "沮丧、抑郁", "deeply depressed"],
    ["sorrowful", "悲伤的（文学）", "a sorrowful song"],
  ]},
  "生气 angry": { related:[], words:[
    ["angry", "生气（通用）", "angry with me"],
    ["annoyed", "恼火、烦", "annoyed by the noise"],
    ["irritated", "被惹恼、不耐烦", "irritated by delays"],
    ["cross", "（口语）生气的", "She's cross with you."],
    ["mad", "（口语）气疯了", "mad at him"],
    ["furious", "暴怒、狂怒", "furious about the lie"],
    ["outraged", "义愤填膺", "outraged by injustice"],
  ]},
  "害怕 afraid": { related:[], words:[
    ["afraid", "害怕（通用，作表语）", "afraid of dogs"],
    ["scared", "（受惊）害怕（口语）", "scared of the dark"],
    ["frightened", "受惊吓的", "frightened by the storm"],
    ["terrified", "极度恐惧（语气强）", "terrified of flying"],
    ["nervous", "紧张、不安", "nervous before the exam"],
    ["anxious", "焦虑、担忧", "anxious about the future"],
    ["panic", "惊慌（名/动）", "panic in the crowd"],
  ]},
  "累 tired": { related:["睡 sleep"], words:[
    ["tired", "累（通用）", "feel tired"],
    ["exhausted", "精疲力竭（语气强）", "completely exhausted"],
    ["weary", "疲惫、厌倦", "weary after work"],
    ["sleepy", "困、想睡", "sleepy in class"],
    ["fatigued", "疲劳的（正式/医学）", "physically fatigued"],
  ]},
  "喜欢 like": { related:["讨厌 hate"], words:[
    ["like", "喜欢（通用）", "like music"],
    ["love", "热爱、爱", "love painting"],
    ["enjoy", "享受、喜爱（+doing）", "enjoy reading"],
    ["adore", "极喜爱、崇拜", "adore her"],
    ["fancy", "喜欢、想要（英式口语）", "fancy a coffee"],
    ["prefer", "更喜欢", "prefer tea to coffee"],
  ]},
  "讨厌 hate": { related:["喜欢 like"], words:[
    ["hate", "讨厌、恨（通用）", "hate Mondays"],
    ["dislike", "不喜欢（较温和、正式）", "dislike the noise"],
    ["loathe", "厌恶（强烈）", "loathe violence"],
    ["detest", "憎恶（正式）", "detest lying"],
    ["despise", "鄙视、看不起", "despise cowards"],
  ]},
  "惊讶 surprised": { related:[], words:[
    ["surprised", "惊讶的（通用）", "surprised by the news"],
    ["amazed", "惊叹、惊奇（多褒）", "amazed at the view"],
    ["astonished", "震惊、大为吃惊", "astonished by the result"],
    ["shocked", "震惊（多负面）", "shocked by the accident"],
    ["stunned", "惊呆、目瞪口呆", "stunned into silence"],
    ["startled", "（突然）吓一跳", "startled by a noise"],
  ]},
  "兴奋 excited": { related:["高兴 happy"], words:[
    ["excited", "兴奋、激动", "excited about the trip"],
    ["thrilled", "激动极了", "thrilled with the gift"],
    ["eager", "渴望的、急切的", "eager to learn"],
    ["enthusiastic", "热情的、热心的", "enthusiastic about sport"],
    ["keen", "热衷的（英式）", "keen on football"],
  ]},

  /* ---------- 描述（形容词）---------- */
  "大 big": { related:["小 small"], words:[
    ["big", "大（口语、通用）", "a big house"],
    ["large", "大（尺寸/数量，正式）", "a large population"],
    ["huge", "巨大的", "a huge success"],
    ["enormous", "庞大的", "an enormous building"],
    ["giant", "巨型的", "a giant wave"],
    ["massive", "（块头）巨大、沉重", "a massive rock"],
    ["vast", "广阔的（面积）", "a vast desert"],
  ]},
  "小 small": { related:["大 big"], words:[
    ["small", "小（尺寸，通用）", "a small room"],
    ["little", "小、少（带感情）", "a cute little dog"],
    ["tiny", "微小的", "a tiny insect"],
    ["miniature", "微型的", "a miniature model"],
    ["minor", "次要的、轻微的", "a minor problem"],
    ["slight", "细微的、轻微的", "a slight change"],
  ]},
  "漂亮 beautiful": { related:[], words:[
    ["beautiful", "美丽的（通用）", "a beautiful view"],
    ["pretty", "漂亮的（多指女性/小巧）", "a pretty girl"],
    ["handsome", "英俊的（多指男性）", "a handsome man"],
    ["gorgeous", "极美的、惊艳", "you look gorgeous"],
    ["attractive", "有吸引力的", "an attractive design"],
    ["lovely", "可爱、宜人的", "a lovely day"],
    ["stunning", "令人惊叹的美", "a stunning sunset"],
    ["cute", "可爱的", "a cute baby"],
  ]},
  "聪明 clever": { related:[], words:[
    ["clever", "聪明、机灵（反应快）", "a clever idea"],
    ["smart", "聪明的（口语，美式）", "a smart kid"],
    ["intelligent", "有智慧的（正式）", "an intelligent answer"],
    ["bright", "（尤指年轻人）聪明", "a bright student"],
    ["wise", "明智、有阅历的", "a wise decision"],
    ["brilliant", "才华横溢、绝妙", "a brilliant scientist"],
  ]},
  "快 fast": { related:["移动 / 走 move"], words:[
    ["fast", "快（速度，形/副）", "a fast car"],
    ["quick", "快速的（短暂、迅速）", "a quick look"],
    ["rapid", "迅速的（变化/增长）", "rapid growth"],
    ["swift", "敏捷的（书面）", "a swift response"],
    ["speedy", "快速的、迅速的", "a speedy recovery"],
  ]},
  "好 good": { related:["坏 bad"], words:[
    ["good", "好（通用）", "a good idea"],
    ["great", "很棒的", "a great movie"],
    ["excellent", "优秀的、极好的", "excellent work"],
    ["wonderful", "精彩、美好的", "a wonderful time"],
    ["fantastic", "了不起的（口语）", "a fantastic result"],
    ["superb", "一流的、卓越的", "superb quality"],
    ["fine", "不错的、挺好的", "a fine performance"],
  ]},
  "坏 bad": { related:["好 good"], words:[
    ["bad", "坏（通用）", "a bad habit"],
    ["awful", "糟糕的、可怕的", "an awful smell"],
    ["terrible", "很糟、骇人的", "a terrible mistake"],
    ["horrible", "可怕、令人不快的", "horrible weather"],
    ["poor", "差的、质量低的", "poor quality"],
    ["nasty", "讨厌的、恶劣的", "a nasty surprise"],
  ]},
  "重要 important": { related:[], words:[
    ["important", "重要的（通用）", "an important decision"],
    ["significant", "显著、有重大意义的", "a significant change"],
    ["crucial", "至关重要、决定性的", "a crucial role"],
    ["vital", "至关重要的（语气强）", "vital information"],
    ["essential", "必不可少的", "essential for life"],
    ["key", "关键的", "a key factor"],
    ["major", "主要的、重大的", "a major issue"],
  ]},
  "安静 quiet": { related:[], words:[
    ["quiet", "安静的（通用）", "a quiet room"],
    ["silent", "寂静、无声的", "fall silent"],
    ["calm", "平静的、镇定的", "stay calm"],
    ["peaceful", "宁静、和平的", "a peaceful village"],
    ["still", "静止的、不动的", "sit still"],
  ]},
  "冷 cold": { related:["热 hot"], words:[
    ["cold", "冷的（通用）", "a cold day"],
    ["cool", "凉爽的（偏舒适）", "a cool breeze"],
    ["chilly", "微冷、有点凉", "a chilly morning"],
    ["freezing", "极冷、冰冻的", "freezing weather"],
    ["icy", "冰冷的、结冰的", "an icy road"],
  ]},
  "热 hot": { related:["冷 cold"], words:[
    ["hot", "热的（通用）", "hot water"],
    ["warm", "温暖的（舒适）", "a warm room"],
    ["boiling", "滚烫的、沸腾的", "boiling hot"],
    ["scorching", "灼热、酷热", "a scorching day"],
    ["mild", "温和的（天气）", "a mild winter"],
  ]},
  "强 strong": { related:["弱 weak"], words:[
    ["strong", "强壮、强大的（通用）", "a strong man"],
    ["powerful", "强有力的、有权势的", "a powerful engine"],
    ["mighty", "强大的（文学/夸张）", "a mighty army"],
    ["tough", "坚韧的、强硬的", "a tough material"],
    ["sturdy", "结实的、坚固的", "a sturdy table"],
  ]},
  "弱 weak": { related:["强 strong"], words:[
    ["weak", "虚弱、弱的（通用）", "feel weak"],
    ["feeble", "（身体）虚弱无力的", "a feeble voice"],
    ["fragile", "易碎的、脆弱的", "fragile glass"],
    ["frail", "（老弱）孱弱的", "a frail old man"],
    ["delicate", "娇弱、精细的", "delicate skin"],
  ]},

  /* ---------- 物品：穿戴 ---------- */
  "鞋 shoes": { related:["衣服 clothes"], words:[
    ["shoe", "鞋（统称）", "a pair of shoes"],
    ["slipper", "拖鞋、便鞋", "wear slippers at home"],
    ["boot", "靴子", "rain boots"],
    ["sandal", "凉鞋", "summer sandals"],
    ["sneaker", "运动鞋（美式）", "white sneakers"],
    ["trainer", "运动鞋（英式）", "a pair of trainers"],
    ["heel", "高跟鞋", "high heels"],
    ["loafer", "乐福鞋、平底便鞋", "leather loafers"],
  ]},
  "衣服 clothes": { related:["鞋 shoes"], words:[
    ["shirt", "衬衫", "a white shirt"],
    ["coat", "外套、大衣", "a winter coat"],
    ["jacket", "夹克", "a leather jacket"],
    ["sweater", "毛衣", "a wool sweater"],
    ["hoodie", "连帽衫", "a grey hoodie"],
    ["dress", "连衣裙", "a summer dress"],
    ["skirt", "半身裙", "a short skirt"],
    ["trousers", "裤子（英式）", "smart trousers"],
    ["suit", "西装、套装", "a business suit"],
  ]},

  /* ---------- 物品：住与家具 ---------- */
  "房子 house": { related:["家具 furniture","房间 room"], words:[
    ["house", "房子（独栋）", "a big house"],
    ["home", "家（含归属感）", "go home"],
    ["flat", "公寓（英式）", "rent a flat"],
    ["apartment", "公寓（美式）", "a city apartment"],
    ["cottage", "小屋、村舍", "a country cottage"],
    ["villa", "别墅", "a seaside villa"],
    ["mansion", "豪宅", "a grand mansion"],
    ["cabin", "小木屋", "a log cabin"],
  ]},
  "家具 furniture": { related:["房子 house"], words:[
    ["chair", "椅子", "sit on a chair"],
    ["sofa", "沙发", "a leather sofa"],
    ["stool", "凳子（无靠背）", "a bar stool"],
    ["bench", "长椅", "a park bench"],
    ["table", "桌子", "a dining table"],
    ["desk", "书桌、办公桌", "a writing desk"],
    ["shelf", "架子", "a book shelf"],
  ]},
  "房间 room": { related:["房子 house"], words:[
    ["bedroom", "卧室", "a cosy bedroom"],
    ["kitchen", "厨房", "cook in the kitchen"],
    ["bathroom", "浴室、卫生间", "use the bathroom"],
    ["living room", "客厅", "relax in the living room"],
    ["hallway", "走廊、门厅", "a narrow hallway"],
    ["attic", "阁楼", "store boxes in the attic"],
    ["basement", "地下室", "a damp basement"],
  ]},

  /* ---------- 物品：出行 ---------- */
  "路 road": { related:["移动 / 走 move","车 vehicle"], words:[
    ["road", "道路（通用、车行）", "a busy road"],
    ["street", "街道（城市、两旁有房）", "a quiet street"],
    ["path", "小路、小径", "a garden path"],
    ["lane", "小巷、车道", "a country lane"],
    ["avenue", "大街、林荫道", "a tree-lined avenue"],
    ["highway", "公路、干道", "a busy highway"],
    ["trail", "（山野）小道", "a hiking trail"],
    ["alley", "胡同、后巷", "a dark alley"],
  ]},
  "车 vehicle": { related:["路 road"], words:[
    ["car", "小汽车", "drive a car"],
    ["bus", "公交车", "take the bus"],
    ["truck", "卡车（美式）", "a delivery truck"],
    ["lorry", "卡车（英式）", "a heavy lorry"],
    ["van", "厢式货车、面包车", "a delivery van"],
    ["taxi", "出租车", "call a taxi"],
    ["motorcycle", "摩托车", "ride a motorcycle"],
  ]},

  /* ---------- 物品：容器与随身 ---------- */
  "容器 cup": { related:["喝 drink","餐具 cutlery"], words:[
    ["cup", "杯子（带把、喝热饮）", "a cup of tea"],
    ["mug", "马克杯（大、厚）", "a coffee mug"],
    ["glass", "玻璃杯", "a glass of water"],
    ["bottle", "瓶子", "a water bottle"],
    ["jar", "罐子（广口、带盖）", "a jam jar"],
    ["bowl", "碗", "a bowl of soup"],
    ["jug", "水壶、有嘴的罐", "a milk jug"],
    ["kettle", "烧水壶", "boil the kettle"],
  ]},
  "包 bag": { related:[], words:[
    ["bag", "包、袋（通用）", "a shopping bag"],
    ["backpack", "双肩背包", "a school backpack"],
    ["handbag", "手提包（女士）", "a leather handbag"],
    ["suitcase", "行李箱", "pack a suitcase"],
    ["purse", "钱包（美式）/小手袋", "a small purse"],
    ["wallet", "钱夹（男士）", "a leather wallet"],
    ["sack", "麻袋、大袋", "a sack of potatoes"],
  ]},

  /* ---------- 身体部位 ---------- */
  "嘴 mouth": { related:["吃 eat","说 speak","脸 face"], words:[
    ["mouth", "嘴", "open your mouth"],
    ["lip", "嘴唇", "red lips"],
    ["tongue", "舌头", "stick out your tongue"],
    ["teeth", "牙齿（复数；单数 tooth）", "brush your teeth"],
    ["jaw", "下巴、颌", "a strong jaw"],
    ["throat", "喉咙", "a sore throat"],
    ["gum", "牙龈", "healthy gums"],
  ]},
  "眼睛 eye": { related:["看 look","脸 face"], words:[
    ["eye", "眼睛", "blue eyes"],
    ["eyebrow", "眉毛", "raise an eyebrow"],
    ["eyelash", "睫毛", "long eyelashes"],
    ["eyelid", "眼皮", "heavy eyelids"],
    ["pupil", "瞳孔（也指学生）", "dilated pupils"],
  ]},
  "脸 face": { related:["嘴 mouth","眼睛 eye","身体 body"], words:[
    ["face", "脸", "wash your face"],
    ["nose", "鼻子", "a runny nose"],
    ["ear", "耳朵", "cover your ears"],
    ["cheek", "脸颊", "rosy cheeks"],
    ["chin", "下巴", "a pointed chin"],
    ["forehead", "额头", "wrinkle your forehead"],
    ["eyebrow", "眉毛", "raise an eyebrow"],
  ]},
  "身体 body": { related:["脸 face"], words:[
    ["head", "头", "nod your head"],
    ["arm", "手臂", "raise your arm"],
    ["leg", "腿", "stretch your legs"],
    ["hand", "手", "wave your hand"],
    ["foot", "脚（复数 feet）", "on foot"],
    ["shoulder", "肩膀", "a sore shoulder"],
    ["knee", "膝盖", "bend your knees"],
    ["chest", "胸部", "chest pain"],
  ]},

  /* ---------- 物品：餐厨 / 学习 / 设备 ---------- */
  "餐具 cutlery": { related:["吃 eat","容器 cup"], words:[
    ["knife", "刀", "a sharp knife"],
    ["fork", "叉子", "use a fork"],
    ["spoon", "勺子", "a soup spoon"],
    ["plate", "盘子", "a dinner plate"],
    ["chopsticks", "筷子", "eat with chopsticks"],
    ["napkin", "餐巾", "a paper napkin"],
  ]},
  "文具 stationery": { related:[], words:[
    ["pen", "钢笔、笔", "write with a pen"],
    ["pencil", "铅笔", "a sharp pencil"],
    ["notebook", "笔记本", "a thick notebook"],
    ["eraser", "橡皮", "use an eraser"],
    ["ruler", "尺子", "a plastic ruler"],
    ["marker", "记号笔", "a black marker"],
  ]},
  "电子设备 device": { related:[], words:[
    ["phone", "手机、电话", "answer the phone"],
    ["computer", "电脑", "use a computer"],
    ["laptop", "笔记本电脑", "a thin laptop"],
    ["tablet", "平板电脑", "read on a tablet"],
    ["screen", "屏幕", "a touch screen"],
    ["keyboard", "键盘", "type on a keyboard"],
  ]},

  /* ---------- 自然 / 类别族 ---------- */
  "天气 weather": { related:[], words:[
    ["rain", "雨", "heavy rain"],
    ["drizzle", "毛毛雨", "a light drizzle"],
    ["shower", "阵雨", "a sudden shower"],
    ["snow", "雪", "fresh snow"],
    ["storm", "暴风雨", "a thunderstorm"],
    ["fog", "雾", "thick fog"],
    ["breeze", "微风", "a gentle breeze"],
    ["thunder", "雷", "thunder and lightning"],
  ]},
  "食物 food": { related:["吃 eat","做饭 cook"], words:[
    ["meal", "一餐、餐食", "a healthy meal"],
    ["snack", "零食、点心", "a quick snack"],
    ["dish", "一道菜", "a tasty dish"],
    ["feast", "盛宴、大餐", "a wedding feast"],
    ["cuisine", "菜系、烹饪风格", "Italian cuisine"],
    ["recipe", "食谱", "follow a recipe"],
  ]},
  "水果 fruit": { related:[], words:[
    ["apple", "苹果", "a red apple"],
    ["banana", "香蕉", "a ripe banana"],
    ["orange", "橙子", "a juicy orange"],
    ["grape", "葡萄", "a bunch of grapes"],
    ["pear", "梨", "a sweet pear"],
    ["peach", "桃子", "a soft peach"],
    ["strawberry", "草莓", "fresh strawberries"],
    ["mango", "芒果", "a ripe mango"],
  ]},
  "动物 animal": { related:[], words:[
    ["dog", "狗", "a pet dog"],
    ["cat", "猫", "a black cat"],
    ["horse", "马", "ride a horse"],
    ["cow", "牛", "a dairy cow"],
    ["sheep", "羊", "a flock of sheep"],
    ["pig", "猪", "a fat pig"],
    ["rabbit", "兔子", "a white rabbit"],
    ["chicken", "鸡", "feed the chickens"],
  ]},
  "植物 plant": { related:[], words:[
    ["tree", "树", "an old tree"],
    ["flower", "花", "pick flowers"],
    ["grass", "草", "green grass"],
    ["bush", "灌木", "a rose bush"],
    ["leaf", "叶子", "fallen leaves"],
    ["root", "根", "deep roots"],
    ["branch", "树枝", "a broken branch"],
    ["seed", "种子", "plant seeds"],
  ]},
  "时间 time": { related:[], words:[
    ["second", "秒", "wait a second"],
    ["minute", "分钟", "five minutes"],
    ["hour", "小时", "an hour later"],
    ["day", "天", "a sunny day"],
    ["week", "周", "next week"],
    ["month", "月", "last month"],
    ["year", "年", "this year"],
    ["decade", "十年", "the past decade"],
  ]},
  "钱 money": { related:["买卖 buy / sell"], words:[
    ["money", "钱（统称、不可数）", "earn money"],
    ["cash", "现金", "pay in cash"],
    ["coin", "硬币", "a gold coin"],
    ["note", "纸币（英式；美式 bill）", "a ten-pound note"],
    ["currency", "货币（某国的）", "foreign currency"],
    ["fund", "资金、基金", "raise funds"],
    ["salary", "薪水", "a monthly salary"],
  ]},

};
